// Curated selection of Devin Night's free VTT token art (TP000-TP020 free
// packs), for the marker/monster token icon picker -- see TODO.md "VTT icon
// picker for marker/monster/NPC tokens". Images live as static files under
// client/public/tokens/, same split as shared/src/boardTiles.ts's
// TILE_MATERIALS (data here, art on disk, no DB/upload involved). Generated
// from what actually shipped in the free bundle -- do not hand-edit `file`
// paths without also touching the file on disk.
//
// Licensing: free for personal/gaming-group use per Devin Night's own terms
// (https://filedn.com/lV1TH8uSVwALfJxGuEcQJX0/TokenUsage.html) -- that page
// also asks to be contacted first, which is being done separately. Credit
// "Devin Night" belongs wherever the app ends up crediting its art sources.
//
// Both `labelDe` and `labelEn` are searchable/shown in the picker -- neither
// replaces the other. `labelEn` is frozen (the original source filename,
// prettified) so search never regresses; `labelDe` starts as a copy of that
// same text and gets replaced item-by-item with a real German name over
// time (pure data edits here, no code/schema change needed for that pass).

export interface TokenIcon {
  /** Stable slug stored on BoardToken.iconAsset -- never the filename. */
  key: string;
  /** Shown in the picker -- a real German name once translated, the English source name until then. */
  labelDe: string;
  /** Frozen original source name -- always searchable alongside labelDe, shown alongside it when they differ. */
  labelEn: string;
  /** Picker category tab. */
  category: string;
  /** Path under client/public/tokens/. */
  file: string;
  artist: string;
}

export const TOKEN_ICONS: TokenIcon[] = [
  { key: "characters-adventurer-dead-22", labelDe: "Abenteurer tot", labelEn: "Adventurer Dead", category: "Charaktere", file: "characters/Adventurer_Dead_22.png", artist: "Devin Night" },
  { key: "characters-adventurer-dead-28", labelDe: "Abenteurer tot", labelEn: "Adventurer Dead", category: "Charaktere", file: "characters/Adventurer_Dead_28.png", artist: "Devin Night" },
  { key: "characters-adventurer-dead-32", labelDe: "Abenteurer tot", labelEn: "Adventurer Dead", category: "Charaktere", file: "characters/Adventurer_Dead_32.png", artist: "Devin Night" },
  { key: "characters-archer-40", labelDe: "Bogenschütze", labelEn: "Archer", category: "Charaktere", file: "characters/Archer_40.png", artist: "Devin Night" },
  { key: "characters-cleric-blue-48", labelDe: "Kleriker Blau", labelEn: "Cleric Blue", category: "Charaktere", file: "characters/Cleric_Blue_48.png", artist: "Devin Night" },
  { key: "characters-cleric-red-47", labelDe: "Kleriker Rot", labelEn: "Cleric Red", category: "Charaktere", file: "characters/Cleric_Red_47.png", artist: "Devin Night" },
  { key: "characters-dwarven-fighter-hammer-03", labelDe: "Zwergen Krieger Hammer", labelEn: "Dwarven Fighter Hammer", category: "Charaktere", file: "characters/Dwarven_fighter_hammer_03.png", artist: "Devin Night" },
  { key: "characters-elven-blue-fighter-09", labelDe: "Elfen Blau Krieger", labelEn: "Elven Blue Fighter", category: "Charaktere", file: "characters/Elven_Blue_fighter_09.png", artist: "Devin Night" },
  { key: "characters-elven-green-archer-02", labelDe: "Elfen Grün Bogenschütze", labelEn: "Elven Green Archer", category: "Charaktere", file: "characters/Elven_Green_Archer_02.png", artist: "Devin Night" },
  { key: "characters-fighter-36", labelDe: "Krieger", labelEn: "Fighter", category: "Charaktere", file: "characters/Fighter_36.png", artist: "Devin Night" },
  { key: "characters-fighter-39", labelDe: "Krieger", labelEn: "Fighter", category: "Charaktere", file: "characters/Fighter_39.png", artist: "Devin Night" },
  { key: "characters-fighter-45", labelDe: "Krieger", labelEn: "Fighter", category: "Charaktere", file: "characters/Fighter_45.png", artist: "Devin Night" },
  { key: "characters-fighter-blue-07", labelDe: "Krieger Blau", labelEn: "Fighter Blue", category: "Charaktere", file: "characters/Fighter_blue_07.png", artist: "Devin Night" },
  { key: "characters-fighter-blue-female-06", labelDe: "Krieger Blau weiblich", labelEn: "Fighter Blue Female", category: "Charaktere", file: "characters/Fighter_Blue_Female_06.png", artist: "Devin Night" },
  { key: "characters-fighter-blue-spear-30", labelDe: "Krieger Blau Speer", labelEn: "Fighter Blue Spear", category: "Charaktere", file: "characters/Fighter_Blue_Spear_30.png", artist: "Devin Night" },
  { key: "characters-fighter-blue-sword-26", labelDe: "Krieger Blau Schwert", labelEn: "Fighter Blue Sword", category: "Charaktere", file: "characters/Fighter_Blue_Sword_26.png", artist: "Devin Night" },
  { key: "characters-fighter-female-35", labelDe: "Krieger weiblich", labelEn: "Fighter Female", category: "Charaktere", file: "characters/Fighter_Female_35.png", artist: "Devin Night" },
  { key: "characters-fighter-female-dagger-34", labelDe: "Krieger weiblich Dolch", labelEn: "Fighter Female Dagger", category: "Charaktere", file: "characters/Fighter_Female_Dagger_34.png", artist: "Devin Night" },
  { key: "characters-fighter-gold-11", labelDe: "Krieger Gold", labelEn: "Fighter Gold", category: "Charaktere", file: "characters/Fighter_Gold_11.png", artist: "Devin Night" },
  { key: "characters-fighter-green-15", labelDe: "Krieger Grün", labelEn: "Fighter Green", category: "Charaktere", file: "characters/Fighter_Green_15.png", artist: "Devin Night" },
  { key: "characters-fighter-mace-24", labelDe: "Krieger Streitkolben", labelEn: "Fighter Mace", category: "Charaktere", file: "characters/Fighter_Mace_24.png", artist: "Devin Night" },
  { key: "characters-fighter-metal-18", labelDe: "Krieger Metall", labelEn: "Fighter Metal", category: "Charaktere", file: "characters/Fighter_Metal_18.png", artist: "Devin Night" },
  { key: "characters-fighter-silver-10", labelDe: "Krieger Silber", labelEn: "Fighter Silver", category: "Charaktere", file: "characters/Fighter_Silver_10.png", artist: "Devin Night" },
  { key: "characters-fighter-spear-purple-29", labelDe: "Krieger Speer Lila", labelEn: "Fighter Spear Purple", category: "Charaktere", file: "characters/Fighter_Spear_Purple_29.png", artist: "Devin Night" },
  { key: "characters-fighter-sword-25", labelDe: "Krieger Schwert", labelEn: "Fighter Sword", category: "Charaktere", file: "characters/Fighter_Sword_25.png", artist: "Devin Night" },
  { key: "characters-fighter-sword-buckler-31", labelDe: "Krieger Schwert Buckler", labelEn: "Fighter Sword Buckler", category: "Charaktere", file: "characters/Fighter_Sword_Buckler_31.png", artist: "Devin Night" },
  { key: "characters-halfling-05", labelDe: "Halbling", labelEn: "Halfling", category: "Charaktere", file: "characters/Halfling_05.png", artist: "Devin Night" },
  { key: "characters-halfling-fighter-41", labelDe: "Halbling Krieger", labelEn: "Halfling Fighter", category: "Charaktere", file: "characters/Halfling_fighter_41.png", artist: "Devin Night" },
  { key: "characters-knight-49", labelDe: "Ritter", labelEn: "Knight", category: "Charaktere", file: "characters/Knight_49.png", artist: "Devin Night" },
  { key: "characters-magicuser-01", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_01.png", artist: "Devin Night" },
  { key: "characters-magicuser-16", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_16.png", artist: "Devin Night" },
  { key: "characters-magicuser-17", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_17.png", artist: "Devin Night" },
  { key: "characters-magicuser-19", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_19.png", artist: "Devin Night" },
  { key: "characters-magicuser-27", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_27.png", artist: "Devin Night" },
  { key: "characters-magicuser-37", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_37.png", artist: "Devin Night" },
  { key: "characters-magicuser-38", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_38.png", artist: "Devin Night" },
  { key: "characters-magicuser-43", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_43.png", artist: "Devin Night" },
  { key: "characters-magicuser-44", labelDe: "Magier", labelEn: "Magicuser", category: "Charaktere", file: "characters/Magicuser_44.png", artist: "Devin Night" },
  { key: "characters-magicuser-green-08", labelDe: "Magier Grün", labelEn: "Magicuser Green", category: "Charaktere", file: "characters/Magicuser_Green_08.png", artist: "Devin Night" },
  { key: "characters-thief-14", labelDe: "Dieb", labelEn: "Thief", category: "Charaktere", file: "characters/Thief_14.png", artist: "Devin Night" },
  { key: "characters-thief-daggers-21", labelDe: "Dieb Dolche", labelEn: "Thief Daggers", category: "Charaktere", file: "characters/Thief_Daggers_21.png", artist: "Devin Night" },
  { key: "characters-villager-female-04", labelDe: "Dorfbewohner weiblich", labelEn: "Villager Female", category: "Charaktere", file: "characters/Villager_Female_04.png", artist: "Devin Night" },
  { key: "characters-whipper-50", labelDe: "Peitscher", labelEn: "Whipper", category: "Charaktere", file: "characters/Whipper_50.png", artist: "Devin Night" },
  { key: "characters-2-car-warrior-sword-sword", labelDe: "Wagen Krieger Schwert Schwert", labelEn: "Car Warrior Sword-sword", category: "Charaktere II", file: "characters-2/Car_Warrior_Sword-Sword.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-barbarian-axe", labelDe: "Zwerg Barbar Axt", labelEn: "Dwarf Barbarian Axe", category: "Charaktere II", file: "characters-2/Dwarf_Barbarian_Axe.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-cleric-morningstar", labelDe: "Zwerg Kleriker Morgenstern", labelEn: "Dwarf Cleric Morningstar", category: "Charaktere II", file: "characters-2/Dwarf_Cleric_Morningstar.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-monk-fist", labelDe: "Zwerg Mönch Faust", labelEn: "Dwarf Monk Fist", category: "Charaktere II", file: "characters-2/Dwarf_Monk_Fist.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-warrior-axe-plate", labelDe: "Zwerg Krieger Axt Plattenrüstung", labelEn: "Dwarf Warrior Axe Plate", category: "Charaktere II", file: "characters-2/Dwarf_warrior_Axe_Plate.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-warrior-crossbow-leather", labelDe: "Zwerg Krieger Armbrust Lederrüstung", labelEn: "Dwarf Warrior Crossbow Leather", category: "Charaktere II", file: "characters-2/Dwarf_Warrior_Crossbow_Leather.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-warrior-mace", labelDe: "Zwerg Krieger Streitkolben", labelEn: "Dwarf Warrior Mace", category: "Charaktere II", file: "characters-2/Dwarf_Warrior_Mace.png", artist: "Devin Night" },
  { key: "characters-2-elf-druid-sickle", labelDe: "Elf Druide Sichel", labelEn: "Elf Druid Sickle", category: "Charaktere II", file: "characters-2/Elf_Druid_Sickle.png", artist: "Devin Night" },
  { key: "characters-2-elf-druid-sickle-leather", labelDe: "Elf Druide Sichel Lederrüstung", labelEn: "Elf Druid Sickle Leather", category: "Charaktere II", file: "characters-2/Elf_Druid_Sickle_Leather.png", artist: "Devin Night" },
  { key: "characters-2-elf-monk-fist", labelDe: "Elf Mönch Faust", labelEn: "Elf Monk Fist", category: "Charaktere II", file: "characters-2/Elf_Monk_Fist.png", artist: "Devin Night" },
  { key: "characters-2-elf-monk-fist-2", labelDe: "Elf Mönch Faust", labelEn: "Elf Monk Fist-2", category: "Charaktere II", file: "characters-2/Elf_Monk_Fist-2.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-bow", labelDe: "Elf Schurke Bogen", labelEn: "Elf Rogue Bow", category: "Charaktere II", file: "characters-2/Elf_Rogue_Bow.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-crossbow", labelDe: "Elf Schurke Armbrust", labelEn: "Elf Rogue Crossbow", category: "Charaktere II", file: "characters-2/Elf_Rogue_Crossbow.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-crossbow-spell", labelDe: "Elf Schurke Armbrust Zauber", labelEn: "Elf Rogue Crossbow-spell", category: "Charaktere II", file: "characters-2/Elf_Rogue_Crossbow-Spell.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-sword-crossbow", labelDe: "Elf Schurke Schwert Armbrust", labelEn: "Elf Rogue Sword-crossbow", category: "Charaktere II", file: "characters-2/Elf_Rogue_Sword-Crossbow.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-two-swords", labelDe: "Elf Schurke zwei Schwerter", labelEn: "Elf Rogue Two-swords", category: "Charaktere II", file: "characters-2/Elf_Rogue_two-swords.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-sword", labelDe: "Elf Krieger Schwert", labelEn: "Elf Warrior Sword", category: "Charaktere II", file: "characters-2/Elf_Warrior_Sword.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-sword-shield", labelDe: "Elf Krieger Schwert Schild", labelEn: "Elf Warrior Sword-shield", category: "Charaktere II", file: "characters-2/Elf_Warrior_Sword-Shield.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow", labelDe: "Elf Krieger Bogenschütze Bogen", labelEn: "Elf Warrior-archer Bow", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather", labelDe: "Elf Krieger Bogenschütze Bogen Lederrüstung", labelEn: "Elf Warrior-archer Bow Leather", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather-2", labelDe: "Elf Krieger Bogenschütze Bogen Lederrüstung", labelEn: "Elf Warrior-archer Bow Leather-2", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather-2.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather-3", labelDe: "Elf Krieger Bogenschütze Bogen Lederrüstung", labelEn: "Elf Warrior-archer Bow Leather-3", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather-3.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather-4", labelDe: "Elf Krieger Bogenschütze Bogen Lederrüstung", labelEn: "Elf Warrior-archer Bow Leather-4", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather-4.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather-5", labelDe: "Elf Krieger Bogenschütze Bogen Lederrüstung", labelEn: "Elf Warrior-archer Bow Leather-5", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather-5.png", artist: "Devin Night" },
  { key: "characters-2-gnome-warrior-sword-shield", labelDe: "Gnom Krieger Schwert Schild", labelEn: "Gnome Warrior Sword-shield", category: "Charaktere II", file: "characters-2/Gnome_Warrior_Sword-Shield.png", artist: "Devin Night" },
  { key: "characters-2-half-elf-wizard-staff", labelDe: "Halb- Elf Magier Stab", labelEn: "Half-elf Wizard Staff", category: "Charaktere II", file: "characters-2/Half-elf_Wizard_Staff.png", artist: "Devin Night" },
  { key: "characters-2-half-orc-warrior-hammer-mace", labelDe: "Halb- Ork Krieger Hammer Streitkolben", labelEn: "Half-orc Warrior Hammer-mace", category: "Charaktere II", file: "characters-2/Half-Orc_Warrior_Hammer-Mace.png", artist: "Devin Night" },
  { key: "characters-2-half-orc-warrior-polearm", labelDe: "Halb- Ork Krieger Stangenwaffe", labelEn: "Half-orc Warrior Polearm", category: "Charaktere II", file: "characters-2/Half-Orc_Warrior_PoleArm.png", artist: "Devin Night" },
  { key: "characters-2-half-orc-warrior-polearm-shield", labelDe: "Halb- Ork Krieger Stangenwaffe Schild", labelEn: "Half-orc Warrior Polearm-shield", category: "Charaktere II", file: "characters-2/Half-Orc_Warrior_PoleArm-Shield.png", artist: "Devin Night" },
  { key: "characters-2-half-orc-warrior-sword", labelDe: "Halb- Ork Krieger Schwert", labelEn: "Half-orc Warrior Sword", category: "Charaktere II", file: "characters-2/Half-Orc_Warrior_Sword.png", artist: "Devin Night" },
  { key: "characters-2-halfling-rogue-daggers", labelDe: "Halbling Schurke Dolche", labelEn: "Halfling Rogue Daggers", category: "Charaktere II", file: "characters-2/Halfling_Rogue_Daggers.png", artist: "Devin Night" },
  { key: "characters-2-human-barbarian-claws", labelDe: "Mensch Barbar Klauen", labelEn: "Human Barbarian Claws", category: "Charaktere II", file: "characters-2/Human_Barbarian_Claws.png", artist: "Devin Night" },
  { key: "characters-2-human-barbarian-sword-shield", labelDe: "Mensch Barbar Schwert Schild", labelEn: "Human Barbarian Sword-shield", category: "Charaktere II", file: "characters-2/Human_Barbarian_Sword-Shield.png", artist: "Devin Night" },
  { key: "characters-2-human-cleric-flail-shield-plate", labelDe: "Mensch Kleriker Kriegsflegel Schild Plattenrüstung", labelEn: "Human Cleric Flail-shield Plate", category: "Charaktere II", file: "characters-2/Human_Cleric_Flail-Shield_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-cleric-holysymbol-shield-plate", labelDe: "Mensch Kleriker Heiliges Symbol Schild Plattenrüstung", labelEn: "Human Cleric Holysymbol-shield Plate", category: "Charaktere II", file: "characters-2/Human_Cleric_HolySymbol-Shield_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-cleric-mace-shield-plate", labelDe: "Mensch Kleriker Streitkolben Schild Plattenrüstung", labelEn: "Human Cleric Mace-shield Plate", category: "Charaktere II", file: "characters-2/Human_Cleric_Mace-Shield_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-mage", labelDe: "Mensch Magier", labelEn: "Human Mage", category: "Charaktere II", file: "characters-2/Human_Mage.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-masked", labelDe: "Mensch Magier maskiert", labelEn: "Human Mage Masked", category: "Charaktere II", file: "characters-2/Human_Mage_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff", labelDe: "Mensch Magier Stab", labelEn: "Human Mage Staff", category: "Charaktere II", file: "characters-2/Human_Mage_Staff.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-masked", labelDe: "Mensch Magier Stab maskiert", labelEn: "Human Mage Staff Masked", category: "Charaktere II", file: "characters-2/Human_Mage_Staff_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-2", labelDe: "Mensch Magier Stab", labelEn: "Human Mage Staff-2", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-2.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-3", labelDe: "Mensch Magier Stab", labelEn: "Human Mage Staff-3", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-3.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-4", labelDe: "Mensch Magier Stab", labelEn: "Human Mage Staff-4", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-4.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-5", labelDe: "Mensch Magier Stab", labelEn: "Human Mage Staff-5", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-5.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-6", labelDe: "Mensch Magier Stab", labelEn: "Human Mage Staff-6", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-6.png", artist: "Devin Night" },
  { key: "characters-2-human-rogue-crossbow", labelDe: "Mensch Schurke Armbrust", labelEn: "Human Rogue Crossbow", category: "Charaktere II", file: "characters-2/Human_Rogue_Crossbow.png", artist: "Devin Night" },
  { key: "characters-2-human-rogue-rapier-crossbow", labelDe: "Mensch Schurke Rapier Armbrust", labelEn: "Human Rogue Rapier-crossbow", category: "Charaktere II", file: "characters-2/Human_Rogue_Rapier-Crossbow.png", artist: "Devin Night" },
  { key: "characters-2-human-rogue-rapier-dagger", labelDe: "Mensch Schurke Rapier Dolch", labelEn: "Human Rogue Rapier-dagger", category: "Charaktere II", file: "characters-2/Human_Rogue_Rapier-Dagger.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-polearm", labelDe: "Mensch Krieger Stangenwaffe", labelEn: "Human Warrior Polearm", category: "Charaktere II", file: "characters-2/Human_Warrior_Polearm.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-spear-masked", labelDe: "Mensch Krieger Speer maskiert", labelEn: "Human Warrior Spear Masked", category: "Charaktere II", file: "characters-2/Human_Warrior_Spear_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-staff-masked", labelDe: "Mensch Krieger Stab maskiert", labelEn: "Human Warrior Staff Masked", category: "Charaktere II", file: "characters-2/Human_Warrior_Staff_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-masked", labelDe: "Mensch Krieger Schwert maskiert", labelEn: "Human Warrior Sword Masked", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-plate", labelDe: "Mensch Krieger Schwert Plattenrüstung", labelEn: "Human Warrior Sword Plate", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield", labelDe: "Mensch Krieger Schwert Schild", labelEn: "Human Warrior Sword-shield", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield-plate", labelDe: "Mensch Krieger Schwert Schild Plattenrüstung", labelEn: "Human Warrior Sword-shield Plate", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield-plate-2", labelDe: "Mensch Krieger Schwert Schild Plattenrüstung", labelEn: "Human Warrior Sword-shield Plate-2", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield_Plate-2.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield-plate-3", labelDe: "Mensch Krieger Schwert Schild Plattenrüstung", labelEn: "Human Warrior Sword-shield Plate-3", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield_Plate-3.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield-2", labelDe: "Mensch Krieger Schwert Schild", labelEn: "Human Warrior Sword-shield-2", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield-2.png", artist: "Devin Night" },
  { key: "characters-2-human-witch-book", labelDe: "Mensch Hexe Buch", labelEn: "Human Witch Book", category: "Charaktere II", file: "characters-2/Human_Witch_Book.png", artist: "Devin Night" },
  { key: "characters-2-thief-rogue-daggers", labelDe: "Dieb Schurke Dolche", labelEn: "Thief Rogue Daggers", category: "Charaktere II", file: "characters-2/Thief_Rogue_Daggers.png", artist: "Devin Night" },
  { key: "characters-2-thief-rogue-sword", labelDe: "Dieb Schurke Schwert", labelEn: "Thief Rogue Sword", category: "Charaktere II", file: "characters-2/Thief_Rogue_Sword.png", artist: "Devin Night" },
  { key: "werecreatures-bear-22", labelDe: "Bär", labelEn: "Bear", category: "Gestaltwandler", file: "werecreatures/bear_22.png", artist: "Devin Night" },
  { key: "werecreatures-bear-24", labelDe: "Bär", labelEn: "Bear", category: "Gestaltwandler", file: "werecreatures/bear_24.png", artist: "Devin Night" },
  { key: "werecreatures-boar-04", labelDe: "Eber", labelEn: "Boar", category: "Gestaltwandler", file: "werecreatures/boar_04.png", artist: "Devin Night" },
  { key: "werecreatures-boar-10", labelDe: "Eber", labelEn: "Boar", category: "Gestaltwandler", file: "werecreatures/boar_10.png", artist: "Devin Night" },
  { key: "werecreatures-boar-16", labelDe: "Eber", labelEn: "Boar", category: "Gestaltwandler", file: "werecreatures/boar_16.png", artist: "Devin Night" },
  { key: "werecreatures-boar-17", labelDe: "Eber", labelEn: "Boar", category: "Gestaltwandler", file: "werecreatures/boar_17.png", artist: "Devin Night" },
  { key: "werecreatures-rat-07", labelDe: "Ratte", labelEn: "Rat", category: "Gestaltwandler", file: "werecreatures/rat_07.png", artist: "Devin Night" },
  { key: "werecreatures-rat-11", labelDe: "Ratte", labelEn: "Rat", category: "Gestaltwandler", file: "werecreatures/rat_11.png", artist: "Devin Night" },
  { key: "werecreatures-rat-32", labelDe: "Ratte", labelEn: "Rat", category: "Gestaltwandler", file: "werecreatures/rat_32.png", artist: "Devin Night" },
  { key: "werecreatures-rat-swarm", labelDe: "Ratte Schwarm", labelEn: "Rat Swarm", category: "Gestaltwandler", file: "werecreatures/rat_swarm.png", artist: "Devin Night" },
  { key: "werecreatures-servant", labelDe: "Diener", labelEn: "Servant", category: "Gestaltwandler", file: "werecreatures/servant.png", artist: "Devin Night" },
  { key: "werecreatures-tiger-27", labelDe: "Tiger", labelEn: "Tiger", category: "Gestaltwandler", file: "werecreatures/tiger_27.png", artist: "Devin Night" },
  { key: "werecreatures-tiger-dark-28", labelDe: "Tiger Dunkel", labelEn: "Tiger Dark", category: "Gestaltwandler", file: "werecreatures/tiger_dark_28.png", artist: "Devin Night" },
  { key: "werecreatures-victim-female-33", labelDe: "Opfer weiblich", labelEn: "Victim Female", category: "Gestaltwandler", file: "werecreatures/victim_female_33.png", artist: "Devin Night" },
  { key: "werecreatures-victim-female-34", labelDe: "Opfer weiblich", labelEn: "Victim Female", category: "Gestaltwandler", file: "werecreatures/victim_female_34.png", artist: "Devin Night" },
  { key: "werecreatures-victim-male-29", labelDe: "Opfer männlich", labelEn: "Victim Male", category: "Gestaltwandler", file: "werecreatures/victim_male_29.png", artist: "Devin Night" },
  { key: "werecreatures-victim-male-30", labelDe: "Opfer männlich", labelEn: "Victim Male", category: "Gestaltwandler", file: "werecreatures/victim_male_30.png", artist: "Devin Night" },
  { key: "werecreatures-victim-male-31", labelDe: "Opfer männlich", labelEn: "Victim Male", category: "Gestaltwandler", file: "werecreatures/victim_male_31.png", artist: "Devin Night" },
  { key: "werecreatures-victim-male-35", labelDe: "Opfer männlich", labelEn: "Victim Male", category: "Gestaltwandler", file: "werecreatures/victim_male_35.png", artist: "Devin Night" },
  { key: "werecreatures-werebear-20", labelDe: "Werbär", labelEn: "Werebear", category: "Gestaltwandler", file: "werecreatures/werebear_20.png", artist: "Devin Night" },
  { key: "werecreatures-werebear-21", labelDe: "Werbär", labelEn: "Werebear", category: "Gestaltwandler", file: "werecreatures/werebear_21.png", artist: "Devin Night" },
  { key: "werecreatures-werebear-25", labelDe: "Werbär", labelEn: "Werebear", category: "Gestaltwandler", file: "werecreatures/werebear_25.png", artist: "Devin Night" },
  { key: "werecreatures-wereboar-15", labelDe: "Wereber", labelEn: "Wereboar", category: "Gestaltwandler", file: "werecreatures/wereboar_15.png", artist: "Devin Night" },
  { key: "werecreatures-wereboar-fighter-09", labelDe: "Wereber Krieger", labelEn: "Wereboar Fighter", category: "Gestaltwandler", file: "werecreatures/wereboar_fighter_09.png", artist: "Devin Night" },
  { key: "werecreatures-wererat-03", labelDe: "Weratte", labelEn: "Wererat", category: "Gestaltwandler", file: "werecreatures/wererat_03.png", artist: "Devin Night" },
  { key: "werecreatures-wererat-05", labelDe: "Weratte", labelEn: "Wererat", category: "Gestaltwandler", file: "werecreatures/wererat_05.png", artist: "Devin Night" },
  { key: "werecreatures-wererat-06", labelDe: "Weratte", labelEn: "Wererat", category: "Gestaltwandler", file: "werecreatures/wererat_06.png", artist: "Devin Night" },
  { key: "werecreatures-wererat-fighter-08", labelDe: "Weratte Krieger", labelEn: "Wererat Fighter", category: "Gestaltwandler", file: "werecreatures/wererat_fighter_08.png", artist: "Devin Night" },
  { key: "werecreatures-weretiger-23", labelDe: "Weretiger", labelEn: "Weretiger", category: "Gestaltwandler", file: "werecreatures/weretiger_23.png", artist: "Devin Night" },
  { key: "werecreatures-weretiger-26", labelDe: "Weretiger", labelEn: "Weretiger", category: "Gestaltwandler", file: "werecreatures/weretiger_26.png", artist: "Devin Night" },
  { key: "werecreatures-werewolf-12", labelDe: "Werwolf", labelEn: "Werewolf", category: "Gestaltwandler", file: "werecreatures/werewolf_12.png", artist: "Devin Night" },
  { key: "werecreatures-werewolf-13", labelDe: "Werwolf", labelEn: "Werewolf", category: "Gestaltwandler", file: "werecreatures/werewolf_13.png", artist: "Devin Night" },
  { key: "werecreatures-werewolf-fighter-14", labelDe: "Werwolf Krieger", labelEn: "Werewolf Fighter", category: "Gestaltwandler", file: "werecreatures/werewolf_fighter_14.png", artist: "Devin Night" },
  { key: "werecreatures-wolf-18", labelDe: "Wolf", labelEn: "Wolf", category: "Gestaltwandler", file: "werecreatures/wolf_18.png", artist: "Devin Night" },
  { key: "werecreatures-wolf-19", labelDe: "Wolf", labelEn: "Wolf", category: "Gestaltwandler", file: "werecreatures/wolf_19.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-archer", labelDe: "Goblin Bogenschütze", labelEn: "Goblin Archer", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_archer.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-archer2", labelDe: "Goblin Bogenschütze", labelEn: "Goblin Archer2", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_archer2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-axeman", labelDe: "Goblin Axtkämpfer", labelEn: "Goblin Axeman", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_axeman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-crossbow", labelDe: "Goblin Armbrust", labelEn: "Goblin Crossbow", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_crossbow.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-crossbow2", labelDe: "Goblin Armbrust", labelEn: "Goblin Crossbow2", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_crossbow2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-crossbow3", labelDe: "Goblin Armbrust", labelEn: "Goblin Crossbow3", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_crossbow3.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-crossbow4", labelDe: "Goblin Armbrust", labelEn: "Goblin Crossbow4", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_crossbow4.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-daggers", labelDe: "Goblin Dolche", labelEn: "Goblin Daggers", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_daggers.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-dead-33", labelDe: "Goblin tot", labelEn: "Goblin Dead", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_dead_33.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-dead-34", labelDe: "Goblin tot", labelEn: "Goblin Dead", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_dead_34.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-fighter", labelDe: "Goblin Krieger", labelEn: "Goblin Fighter", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_fighter.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-mace", labelDe: "Goblin Streitkolben", labelEn: "Goblin Mace", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_mace.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-shaman", labelDe: "Goblin Schamane", labelEn: "Goblin Shaman", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_shaman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-shaman2", labelDe: "Goblin Schamane", labelEn: "Goblin Shaman2", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_shaman2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-shaman3", labelDe: "Goblin Schamane", labelEn: "Goblin Shaman3", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_shaman3.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-shaman4", labelDe: "Goblin Schamane", labelEn: "Goblin Shaman4", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_shaman4.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-spearman", labelDe: "Goblin Speerkämpfer", labelEn: "Goblin Spearman", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_spearman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-swordsman", labelDe: "Goblin Schwertkämpfer", labelEn: "Goblin Swordsman", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_swordsman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-archer", labelDe: "Kobold Bogenschütze", labelEn: "Kobold Archer", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_archer.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-dead-06", labelDe: "Kobold tot", labelEn: "Kobold Dead", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_dead_06.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-dead-12", labelDe: "Kobold tot", labelEn: "Kobold Dead", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_dead_12.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter", labelDe: "Kobold Krieger", labelEn: "Kobold Fighter", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter2", labelDe: "Kobold Krieger", labelEn: "Kobold Fighter2", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter3", labelDe: "Kobold Krieger", labelEn: "Kobold Fighter3", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter3.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter4", labelDe: "Kobold Krieger", labelEn: "Kobold Fighter4", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter4.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter5", labelDe: "Kobold Krieger", labelEn: "Kobold Fighter5", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter5.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-shaman1", labelDe: "Kobold Schamane", labelEn: "Kobold Shaman1", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_shaman1.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-shaman2", labelDe: "Kobold Schamane", labelEn: "Kobold Shaman2", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_shaman2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-spearman", labelDe: "Kobold Speerkämpfer", labelEn: "Kobold Spearman", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_spearman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-worg-22", labelDe: "Worg", labelEn: "Worg", category: "Goblins & Kobolde", file: "goblins-kobolds/worg_22.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-berserker", labelDe: "Oger Berserker", labelEn: "Ogre Berserker", category: "Orks & Trolle", file: "orcs-trolls/Ogre_berserker.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-dead-28", labelDe: "Oger tot", labelEn: "Ogre Dead", category: "Orks & Trolle", file: "orcs-trolls/Ogre_dead_28.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-dead-29", labelDe: "Oger tot", labelEn: "Ogre Dead", category: "Orks & Trolle", file: "orcs-trolls/Ogre_dead_29.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter", labelDe: "Oger Krieger", labelEn: "Ogre Fighter", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter2", labelDe: "Oger Krieger", labelEn: "Ogre Fighter2", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter2.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter3", labelDe: "Oger Krieger", labelEn: "Ogre Fighter3", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter3.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter4", labelDe: "Oger Krieger", labelEn: "Ogre Fighter4", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter4.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter5", labelDe: "Oger Krieger", labelEn: "Ogre Fighter5", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter5.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter6", labelDe: "Oger Krieger", labelEn: "Ogre Fighter6", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter6.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-shaman", labelDe: "Oger Schamane", labelEn: "Ogre Shaman", category: "Orks & Trolle", file: "orcs-trolls/Ogre_shaman.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-shaman2", labelDe: "Oger Schamane", labelEn: "Ogre Shaman2", category: "Orks & Trolle", file: "orcs-trolls/Ogre_shaman2.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-archer", labelDe: "Ork Bogenschütze", labelEn: "Orc Archer", category: "Orks & Trolle", file: "orcs-trolls/Orc_archer.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-chieftan", labelDe: "Ork Häuptling", labelEn: "Orc Chieftan", category: "Orks & Trolle", file: "orcs-trolls/Orc_chieftan.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-chieftan2", labelDe: "Ork Häuptling", labelEn: "Orc Chieftan2", category: "Orks & Trolle", file: "orcs-trolls/Orc_chieftan2.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-crossbowman", labelDe: "Ork Armbrustschütze", labelEn: "Orc Crossbowman", category: "Orks & Trolle", file: "orcs-trolls/Orc_crossbowman.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter", labelDe: "Ork Krieger", labelEn: "Orc Fighter", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter2", labelDe: "Ork Krieger", labelEn: "Orc Fighter2", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter2.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter3", labelDe: "Ork Krieger", labelEn: "Orc Fighter3", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter3.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter4", labelDe: "Ork Krieger", labelEn: "Orc Fighter4", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter4.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter5", labelDe: "Ork Krieger", labelEn: "Orc Fighter5", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter5.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter6", labelDe: "Ork Krieger", labelEn: "Orc Fighter6", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter6.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter7", labelDe: "Ork Krieger", labelEn: "Orc Fighter7", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter7.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-shaman", labelDe: "Ork Schamane", labelEn: "Orc Shaman", category: "Orks & Trolle", file: "orcs-trolls/Orc_shaman.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-dead-27", labelDe: "Troll tot", labelEn: "Troll Dead", category: "Orks & Trolle", file: "orcs-trolls/Troll_dead_27.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter", labelDe: "Troll Krieger", labelEn: "Troll Fighter", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter1", labelDe: "Troll Krieger", labelEn: "Troll Fighter1", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter1.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter2", labelDe: "Troll Krieger", labelEn: "Troll Fighter2", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter2.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter3", labelDe: "Troll Krieger", labelEn: "Troll Fighter3", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter3.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter4", labelDe: "Troll Krieger", labelEn: "Troll Fighter4", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter4.png", artist: "Devin Night" },
  { key: "pirates-dog-hound", labelDe: "Hund Jagdhund", labelEn: "Dog Hound", category: "Piraten", file: "pirates/dog_hound.png", artist: "Devin Night" },
  { key: "pirates-female-blacksmith-hammer", labelDe: "weiblich Schmied Hammer", labelEn: "Female Blacksmith Hammer", category: "Piraten", file: "pirates/female_blacksmith_hammer.png", artist: "Devin Night" },
  { key: "pirates-female-captian-sword", labelDe: "weiblich Hauptmann Schwert", labelEn: "Female Captain Sword", category: "Piraten", file: "pirates/female_captian_sword.png", artist: "Devin Night" },
  { key: "pirates-female-cleaver", labelDe: "weiblich Hackbeil", labelEn: "Female Cleaver", category: "Piraten", file: "pirates/female_cleaver.png", artist: "Devin Night" },
  { key: "pirates-female-lady-dress", labelDe: "weiblich Lady Kleid", labelEn: "Female Lady Dress", category: "Piraten", file: "pirates/female_lady_dress.png", artist: "Devin Night" },
  { key: "pirates-female-long-knife", labelDe: "weiblich lang Messer", labelEn: "Female Long Knife", category: "Piraten", file: "pirates/female_long_knife.png", artist: "Devin Night" },
  { key: "pirates-female-mage-spell", labelDe: "weiblich Magier Zauber", labelEn: "Female Mage Spell", category: "Piraten", file: "pirates/female_mage_spell.png", artist: "Devin Night" },
  { key: "pirates-female-shortsword", labelDe: "weiblich Kurzschwert", labelEn: "Female Shortsword", category: "Piraten", file: "pirates/female_shortsword.png", artist: "Devin Night" },
  { key: "pirates-female-sword-tattoo", labelDe: "weiblich Schwert Tätowierung", labelEn: "Female Sword Tattoo", category: "Piraten", file: "pirates/female_sword_tattoo.png", artist: "Devin Night" },
  { key: "pirates-female-wild-mage", labelDe: "weiblich wild Magier", labelEn: "Female Wild Mage", category: "Piraten", file: "pirates/female_wild_mage.png", artist: "Devin Night" },
  { key: "pirates-female-young-running", labelDe: "weiblich jung laufend", labelEn: "Female Young Running", category: "Piraten", file: "pirates/female_young_running.png", artist: "Devin Night" },
  { key: "pirates-male-axe-fighter", labelDe: "männlich Axt Krieger", labelEn: "Male Axe Fighter", category: "Piraten", file: "pirates/male_axe_fighter.png", artist: "Devin Night" },
  { key: "pirates-male-blunderbus-canon", labelDe: "männlich Donnerbüchse Kanone", labelEn: "Male Blunderbus Cannon", category: "Piraten", file: "pirates/male_blunderbus_canon.png", artist: "Devin Night" },
  { key: "pirates-male-captain-sword", labelDe: "männlich Hauptmann Schwert", labelEn: "Male Captain Sword", category: "Piraten", file: "pirates/male_captain_sword.png", artist: "Devin Night" },
  { key: "pirates-male-captain-trident", labelDe: "männlich Hauptmann Dreizack", labelEn: "Male Captain Trident", category: "Piraten", file: "pirates/male_captain_trident.png", artist: "Devin Night" },
  { key: "pirates-male-crossbow", labelDe: "männlich Armbrust", labelEn: "Male Crossbow", category: "Piraten", file: "pirates/male_crossbow.png", artist: "Devin Night" },
  { key: "pirates-male-crossbow-large", labelDe: "männlich Armbrust groß", labelEn: "Male Crossbow Large", category: "Piraten", file: "pirates/male_crossbow_large.png", artist: "Devin Night" },
  { key: "pirates-male-grappling-hook-boarder", labelDe: "männlich ringend Haken Enterer", labelEn: "Male Grappling Hook Boarder", category: "Piraten", file: "pirates/male_grappling_hook_boarder.png", artist: "Devin Night" },
  { key: "pirates-male-katana-eyepatch", labelDe: "männlich Katana Augenklappe", labelEn: "Male Katana Eyepatch", category: "Piraten", file: "pirates/male_katana_eyepatch.png", artist: "Devin Night" },
  { key: "pirates-male-knife-urchin", labelDe: "männlich Messer Gassenkind", labelEn: "Male Knife Urchin", category: "Piraten", file: "pirates/male_knife_urchin.png", artist: "Devin Night" },
  { key: "pirates-male-mage", labelDe: "männlich Magier", labelEn: "Male Mage", category: "Piraten", file: "pirates/male_mage.png", artist: "Devin Night" },
  { key: "pirates-male-noble-diplomat", labelDe: "männlich Adliger Diplomat", labelEn: "Male Noble Diplomat", category: "Piraten", file: "pirates/male_noble_diplomat.png", artist: "Devin Night" },
  { key: "pirates-male-pirate-crossbow", labelDe: "männlich Pirat Armbrust", labelEn: "Male Pirate Crossbow", category: "Piraten", file: "pirates/male_pirate_crossbow.png", artist: "Devin Night" },
  { key: "pirates-male-pirate-swrod-shield", labelDe: "männlich Pirat Schwert Schild", labelEn: "Male Pirate Sword Shield", category: "Piraten", file: "pirates/male_pirate_swrod_shield.png", artist: "Devin Night" },
  { key: "pirates-male-purple-rapier", labelDe: "männlich Lila Rapier", labelEn: "Male Purple Rapier", category: "Piraten", file: "pirates/male_purple_rapier.png", artist: "Devin Night" },
  { key: "pirates-male-rapier-figher", labelDe: "männlich Rapier Krieger", labelEn: "Male Rapier Fighter", category: "Piraten", file: "pirates/male_rapier_figher.png", artist: "Devin Night" },
  { key: "pirates-male-red-sword", labelDe: "männlich Rot Schwert", labelEn: "Male Red Sword", category: "Piraten", file: "pirates/male_red_sword.png", artist: "Devin Night" },
  { key: "pirates-male-rower-left", labelDe: "männlich Ruderer links", labelEn: "Male Rower Left", category: "Piraten", file: "pirates/male_rower_left.png", artist: "Devin Night" },
  { key: "pirates-male-rower-middle", labelDe: "männlich Ruderer mittel", labelEn: "Male Rower Middle", category: "Piraten", file: "pirates/male_rower_middle.png", artist: "Devin Night" },
  { key: "pirates-male-rower-oars", labelDe: "männlich Ruderer Ruder", labelEn: "Male Rower Oars", category: "Piraten", file: "pirates/male_rower_oars.png", artist: "Devin Night" },
  { key: "pirates-male-rower-right", labelDe: "männlich Ruderer rechts", labelEn: "Male Rower Right", category: "Piraten", file: "pirates/male_rower_right.png", artist: "Devin Night" },
  { key: "pirates-male-rowers-left", labelDe: "männlich Ruderer links", labelEn: "Male Rowers Left", category: "Piraten", file: "pirates/male_rowers_left.png", artist: "Devin Night" },
  { key: "pirates-male-rowers-right", labelDe: "männlich Ruderer rechts", labelEn: "Male Rowers Right", category: "Piraten", file: "pirates/male_rowers_right.png", artist: "Devin Night" },
  { key: "pirates-male-sunburnt-brawler", labelDe: "männlich sonnenverbrannt Raufbold", labelEn: "Male Sunburnt Brawler", category: "Piraten", file: "pirates/male_sunburnt_brawler.png", artist: "Devin Night" },
  { key: "pirates-male-sword", labelDe: "männlich Schwert", labelEn: "Male Sword", category: "Piraten", file: "pirates/male_sword.png", artist: "Devin Night" },
  { key: "pirates-male-sword-dagger", labelDe: "männlich Schwert Dolch", labelEn: "Male Sword Dagger", category: "Piraten", file: "pirates/male_sword_dagger.png", artist: "Devin Night" },
  { key: "pirates-male-sword-hook", labelDe: "männlich Schwert Haken", labelEn: "Male Sword Hook", category: "Piraten", file: "pirates/male_sword_hook.png", artist: "Devin Night" },
  { key: "pirates-male-sword-stalker", labelDe: "männlich Schwert Schleicher", labelEn: "Male Sword Stalker", category: "Piraten", file: "pirates/male_sword_stalker.png", artist: "Devin Night" },
  { key: "pirates-male-swordsman-scimitar", labelDe: "männlich Schwertkämpfer Krummsäbel", labelEn: "Male Swordsman Scimitar", category: "Piraten", file: "pirates/male_swordsman_scimitar.png", artist: "Devin Night" },
  { key: "pirates-male-viking-axe", labelDe: "männlich Wikinger Axt", labelEn: "Male Viking Axe", category: "Piraten", file: "pirates/male_viking_axe.png", artist: "Devin Night" },
  { key: "pirates-male-viking-axe-shiled", labelDe: "männlich Wikinger Axt Schild", labelEn: "Male Viking Axe Shield", category: "Piraten", file: "pirates/male_viking_axe_shiled.png", artist: "Devin Night" },
  { key: "dm-essentials-bullman-poleaxe", labelDe: "Stiermensch Stangenaxt", labelEn: "Bullman Poleaxe", category: "SL-Extras", file: "dm-essentials/bullman_poleaxe.png", artist: "Devin Night" },
  { key: "dm-essentials-chimera", labelDe: "Chimäre", labelEn: "Chimera", category: "SL-Extras", file: "dm-essentials/chimera.png", artist: "Devin Night" },
  { key: "dm-essentials-gryphon", labelDe: "Greif", labelEn: "Gryphon", category: "SL-Extras", file: "dm-essentials/gryphon.png", artist: "Devin Night" },
  { key: "dm-essentials-harpy-1", labelDe: "Harpyie", labelEn: "Harpy", category: "SL-Extras", file: "dm-essentials/harpy_1.png", artist: "Devin Night" },
  { key: "dm-essentials-harpy-brown-flying", labelDe: "Harpyie Braun fliegend", labelEn: "Harpy Brown Flying", category: "SL-Extras", file: "dm-essentials/harpy_brown_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-harpy-purple", labelDe: "Harpyie Lila", labelEn: "Harpy Purple", category: "SL-Extras", file: "dm-essentials/harpy_purple.png", artist: "Devin Night" },
  { key: "dm-essentials-harpy-purple-flying", labelDe: "Harpyie Lila fliegend", labelEn: "Harpy Purple Flying", category: "SL-Extras", file: "dm-essentials/harpy_purple_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-hippogriff", labelDe: "Hippogreif", labelEn: "Hippogriff", category: "SL-Extras", file: "dm-essentials/hippogriff.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra-1head", labelDe: "Hydra 1-köpfig", labelEn: "Hydra 1head", category: "SL-Extras", file: "dm-essentials/hydra_1head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra-2head", labelDe: "Hydra 2-köpfig", labelEn: "Hydra 2head", category: "SL-Extras", file: "dm-essentials/hydra_2head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra-5head", labelDe: "Hydra 5-köpfig", labelEn: "Hydra 5head", category: "SL-Extras", file: "dm-essentials/hydra_5head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra-8head", labelDe: "Hydra 8-köpfig", labelEn: "Hydra 8head", category: "SL-Extras", file: "dm-essentials/hydra_8head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra2-1head", labelDe: "Hydra 1-köpfig", labelEn: "Hydra2 1head", category: "SL-Extras", file: "dm-essentials/hydra2_1head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra2-2headed", labelDe: "Hydra 2-köpfig", labelEn: "Hydra2 2headed", category: "SL-Extras", file: "dm-essentials/hydra2_2headed.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra2-8head", labelDe: "Hydra 8-köpfig", labelEn: "Hydra2 8head", category: "SL-Extras", file: "dm-essentials/hydra2_8head.png", artist: "Devin Night" },
  { key: "dm-essentials-jhydra2-5head", labelDe: "Hydra 5-köpfig", labelEn: "Hydra2 5head", category: "SL-Extras", file: "dm-essentials/jhydra2_5head.png", artist: "Devin Night" },
  { key: "dm-essentials-lion", labelDe: "Löwe", labelEn: "Lion", category: "SL-Extras", file: "dm-essentials/lion.png", artist: "Devin Night" },
  { key: "dm-essentials-lion-winged", labelDe: "Löwe geflügelt", labelEn: "Lion Winged", category: "SL-Extras", file: "dm-essentials/lion_winged.png", artist: "Devin Night" },
  { key: "dm-essentials-manticore-flying", labelDe: "Mantikor fliegend", labelEn: "Manticore Flying", category: "SL-Extras", file: "dm-essentials/manticore_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-manticore-ground", labelDe: "Mantikor am Boden", labelEn: "Manticore Ground", category: "SL-Extras", file: "dm-essentials/manticore_ground.png", artist: "Devin Night" },
  { key: "dm-essentials-medusa-red", labelDe: "Medusa Rot", labelEn: "Medusa Red", category: "SL-Extras", file: "dm-essentials/medusa_red.png", artist: "Devin Night" },
  { key: "dm-essentials-medusa-tan", labelDe: "Medusa Beige", labelEn: "Medusa Tan", category: "SL-Extras", file: "dm-essentials/medusa_tan.png", artist: "Devin Night" },
  { key: "dm-essentials-minotaur-axe", labelDe: "Minotaurus Axt", labelEn: "Minotaur Axe", category: "SL-Extras", file: "dm-essentials/minotaur_axe.png", artist: "Devin Night" },
  { key: "dm-essentials-minotaur-axe-2", labelDe: "Minotaurus Axt", labelEn: "Minotaur Axe", category: "SL-Extras", file: "dm-essentials/minotaur_axe_2.png", artist: "Devin Night" },
  { key: "dm-essentials-minotaur-axe-3", labelDe: "Minotaurus Axt", labelEn: "Minotaur Axe", category: "SL-Extras", file: "dm-essentials/minotaur_axe_3.png", artist: "Devin Night" },
  { key: "dm-essentials-satyr-axe", labelDe: "Satyr Axt", labelEn: "Satyr Axe", category: "SL-Extras", file: "dm-essentials/satyr_axe.png", artist: "Devin Night" },
  { key: "dm-essentials-satyr-staff", labelDe: "Satyr Stab", labelEn: "Satyr Staff", category: "SL-Extras", file: "dm-essentials/satyr_staff.png", artist: "Devin Night" },
  { key: "dm-essentials-satyr-staff-2", labelDe: "Satyr Stab", labelEn: "Satyr Staff", category: "SL-Extras", file: "dm-essentials/satyr_staff_2.png", artist: "Devin Night" },
  { key: "dm-essentials-satyr-whip", labelDe: "Satyr Peitsche", labelEn: "Satyr Whip", category: "SL-Extras", file: "dm-essentials/satyr_whip.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-2headed", labelDe: "Wyvern 2-köpfig", labelEn: "Wyvern 2headed", category: "SL-Extras", file: "dm-essentials/wyvern_2headed.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-blue", labelDe: "Wyvern Blau", labelEn: "Wyvern Blue", category: "SL-Extras", file: "dm-essentials/wyvern_blue.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-blue-flying", labelDe: "Wyvern Blau fliegend", labelEn: "Wyvern Blue Flying", category: "SL-Extras", file: "dm-essentials/wyvern_blue_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-blue-ground", labelDe: "Wyvern Blau am Boden", labelEn: "Wyvern Blue Ground", category: "SL-Extras", file: "dm-essentials/wyvern_blue_ground.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-green", labelDe: "Wyvern Grün", labelEn: "Wyvern Green", category: "SL-Extras", file: "dm-essentials/wyvern_green.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-green-flying", labelDe: "Wyvern Grün fliegend", labelEn: "Wyvern Green Flying", category: "SL-Extras", file: "dm-essentials/wyvern_green_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-green-sitting", labelDe: "Wyvern Grün sitzend", labelEn: "Wyvern Green Sitting", category: "SL-Extras", file: "dm-essentials/wyvern_green_sitting.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-purple", labelDe: "Wyvern Lila", labelEn: "Wyvern Purple", category: "SL-Extras", file: "dm-essentials/wyvern_purple.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-tan-flying", labelDe: "Wyvern Beige fliegend", labelEn: "Wyvern Tan Flying", category: "SL-Extras", file: "dm-essentials/wyvern_tan_flying.png", artist: "Devin Night" },
  { key: "townsfolk-bartender-male", labelDe: "Wirt männlich", labelEn: "Bartender Male", category: "Stadtvolk", file: "townsfolk/bartender_male.png", artist: "Devin Night" },
  { key: "townsfolk-blacksmith-male", labelDe: "Schmied männlich", labelEn: "Blacksmith Male", category: "Stadtvolk", file: "townsfolk/blacksmith_male.png", artist: "Devin Night" },
  { key: "townsfolk-boy-running", labelDe: "Junge laufend", labelEn: "Boy Running", category: "Stadtvolk", file: "townsfolk/boy_running.png", artist: "Devin Night" },
  { key: "townsfolk-boy-stick", labelDe: "Junge Stock", labelEn: "Boy Stick", category: "Stadtvolk", file: "townsfolk/boy_stick.png", artist: "Devin Night" },
  { key: "townsfolk-builder-male", labelDe: "Baumeister männlich", labelEn: "Builder Male", category: "Stadtvolk", file: "townsfolk/builder_male.png", artist: "Devin Night" },
  { key: "townsfolk-buthcer-male", labelDe: "Metzger männlich", labelEn: "Butcher Male", category: "Stadtvolk", file: "townsfolk/buthcer_male.png", artist: "Devin Night" },
  { key: "townsfolk-cows", labelDe: "Kühe", labelEn: "Cows", category: "Stadtvolk", file: "townsfolk/cows.png", artist: "Devin Night" },
  { key: "townsfolk-farmer-rake", labelDe: "Bauer Rechen", labelEn: "Farmer Rake", category: "Stadtvolk", file: "townsfolk/farmer_rake.png", artist: "Devin Night" },
  { key: "townsfolk-florist-lady", labelDe: "Florist Lady", labelEn: "Florist Lady", category: "Stadtvolk", file: "townsfolk/florist_lady.png", artist: "Devin Night" },
  { key: "townsfolk-gardener-male", labelDe: "Gärtner männlich", labelEn: "Gardener Male", category: "Stadtvolk", file: "townsfolk/gardener_male.png", artist: "Devin Night" },
  { key: "townsfolk-gilr-red", labelDe: "Mädchen Rot", labelEn: "Girl Red", category: "Stadtvolk", file: "townsfolk/gilr_red.png", artist: "Devin Night" },
  { key: "townsfolk-girl-blue", labelDe: "Mädchen Blau", labelEn: "Girl Blue", category: "Stadtvolk", file: "townsfolk/girl_blue.png", artist: "Devin Night" },
  { key: "townsfolk-half-orc-bartender", labelDe: "Halb- Ork Wirt", labelEn: "Half Orc Bartender", category: "Stadtvolk", file: "townsfolk/half_orc_bartender.png", artist: "Devin Night" },
  { key: "townsfolk-hunter-trapper", labelDe: "Jäger Fallensteller", labelEn: "Hunter Trapper", category: "Stadtvolk", file: "townsfolk/hunter_trapper.png", artist: "Devin Night" },
  { key: "townsfolk-local-female", labelDe: "ansässig weiblich", labelEn: "Local Female", category: "Stadtvolk", file: "townsfolk/local_female.png", artist: "Devin Night" },
  { key: "townsfolk-local-female-2", labelDe: "ansässig weiblich", labelEn: "Local Female", category: "Stadtvolk", file: "townsfolk/local_female_2.png", artist: "Devin Night" },
  { key: "townsfolk-local-male", labelDe: "ansässig männlich", labelEn: "Local Male", category: "Stadtvolk", file: "townsfolk/local_male.png", artist: "Devin Night" },
  { key: "townsfolk-local-male-2", labelDe: "ansässig männlich", labelEn: "Local Male", category: "Stadtvolk", file: "townsfolk/local_male_2.png", artist: "Devin Night" },
  { key: "townsfolk-merchant-female-wizard", labelDe: "Händler weiblich Magier", labelEn: "Merchant Female Wizard", category: "Stadtvolk", file: "townsfolk/merchant_female_wizard.png", artist: "Devin Night" },
  { key: "townsfolk-minor-noble-female", labelDe: "klein Adliger weiblich", labelEn: "Minor Noble Female", category: "Stadtvolk", file: "townsfolk/minor_noble_female.png", artist: "Devin Night" },
  { key: "townsfolk-minor-noble-male", labelDe: "klein Adliger männlich", labelEn: "Minor Noble Male", category: "Stadtvolk", file: "townsfolk/minor_noble_male.png", artist: "Devin Night" },
  { key: "townsfolk-packbearer-porter", labelDe: "Lastenträger Träger", labelEn: "Packbearer Porter", category: "Stadtvolk", file: "townsfolk/packbearer_porter.png", artist: "Devin Night" },
  { key: "townsfolk-peasant-farmer-hay", labelDe: "Bauer Bauer Heu", labelEn: "Peasant Farmer Hay", category: "Stadtvolk", file: "townsfolk/Peasant_farmer_hay.png", artist: "Devin Night" },
  { key: "townsfolk-peasant-water-fetcher", labelDe: "Wasserträger", labelEn: "Peasant Water Fetcher", category: "Stadtvolk", file: "townsfolk/Peasant_water_fetcher.png", artist: "Devin Night" },
  { key: "townsfolk-porter-male", labelDe: "Träger männlich", labelEn: "Porter Male", category: "Stadtvolk", file: "townsfolk/porter_male.png", artist: "Devin Night" },
  { key: "townsfolk-scholar-female", labelDe: "Gelehrter weiblich", labelEn: "Scholar Female", category: "Stadtvolk", file: "townsfolk/scholar_female.png", artist: "Devin Night" },
  { key: "townsfolk-scholar-female-2", labelDe: "Gelehrter weiblich", labelEn: "Scholar Female", category: "Stadtvolk", file: "townsfolk/scholar_female_2.png", artist: "Devin Night" },
  { key: "townsfolk-server-male", labelDe: "Kellner männlich", labelEn: "Server Male", category: "Stadtvolk", file: "townsfolk/server_male.png", artist: "Devin Night" },
  { key: "undead-female-ghost-blue-2", labelDe: "weiblich Geist Blau", labelEn: "Female Ghost Blue", category: "Untote", file: "undead/female_ghost_blue_2.png", artist: "Devin Night" },
  { key: "undead-ghost-female-blue", labelDe: "Geist weiblich Blau", labelEn: "Ghost Female Blue", category: "Untote", file: "undead/ghost_female_blue.png", artist: "Devin Night" },
  { key: "undead-ghost-white-evil", labelDe: "Geist Weiß böse", labelEn: "Ghost White Evil", category: "Untote", file: "undead/ghost_white_evil.png", artist: "Devin Night" },
  { key: "undead-ghost-wolf-silver", labelDe: "Geist Wolf Silber", labelEn: "Ghost Wolf Silver", category: "Untote", file: "undead/ghost_wolf_silver.png", artist: "Devin Night" },
  { key: "undead-lich-blue", labelDe: "Lich Blau", labelEn: "Lich Blue", category: "Untote", file: "undead/lich_blue.png", artist: "Devin Night" },
  { key: "undead-lich-masked-mage", labelDe: "Lich maskiert Magier", labelEn: "Lich Masked Mage", category: "Untote", file: "undead/lich_masked_mage.png", artist: "Devin Night" },
  { key: "undead-lich-skull-evil", labelDe: "Lich Schädel böse", labelEn: "Lich Skull Evil", category: "Untote", file: "undead/lich_skull_evil.png", artist: "Devin Night" },
  { key: "undead-skeleton-archer-red", labelDe: "Skelett Bogenschütze Rot", labelEn: "Skeleton Archer Red", category: "Untote", file: "undead/skeleton_archer_red.png", artist: "Devin Night" },
  { key: "undead-skeleton-archer-walking", labelDe: "Skelett Bogenschütze gehend", labelEn: "Skeleton Archer Walking", category: "Untote", file: "undead/skeleton_archer_walking.png", artist: "Devin Night" },
  { key: "undead-skeleton-axe", labelDe: "Skelett Axt", labelEn: "Skeleton Axe", category: "Untote", file: "undead/skeleton_axe.png", artist: "Devin Night" },
  { key: "undead-skeleton-axe-shield", labelDe: "Skelett Axt Schild", labelEn: "Skeleton Axe Shield", category: "Untote", file: "undead/skeleton_axe_shield.png", artist: "Devin Night" },
  { key: "undead-skeleton-crawling-legless", labelDe: "Skelett kriechend beinlos", labelEn: "Skeleton Crawling Legless", category: "Untote", file: "undead/skeleton_crawling_legless.png", artist: "Devin Night" },
  { key: "undead-skeleton-crossbow", labelDe: "Skelett Armbrust", labelEn: "Skeleton Crossbow", category: "Untote", file: "undead/skeleton_crossbow.png", artist: "Devin Night" },
  { key: "undead-skeleton-crossbow-armored", labelDe: "Skelett Armbrust gepanzert", labelEn: "Skeleton Crossbow Armored", category: "Untote", file: "undead/skeleton_crossbow_armored.png", artist: "Devin Night" },
  { key: "undead-skeleton-dagger", labelDe: "Skelett Dolch", labelEn: "Skeleton Dagger", category: "Untote", file: "undead/skeleton_dagger.png", artist: "Devin Night" },
  { key: "undead-skeleton-mace", labelDe: "Skelett Streitkolben", labelEn: "Skeleton Mace", category: "Untote", file: "undead/skeleton_mace.png", artist: "Devin Night" },
  { key: "undead-skeleton-sword-shield", labelDe: "Skelett Schwert Schild", labelEn: "Skeleton Sword Shield", category: "Untote", file: "undead/skeleton_sword_shield.png", artist: "Devin Night" },
  { key: "undead-wight-bone", labelDe: "Wiedergänger Knochen", labelEn: "Wight Bone", category: "Untote", file: "undead/wight_bone.png", artist: "Devin Night" },
  { key: "undead-wight-bone-club", labelDe: "Wiedergänger Knochen Keule", labelEn: "Wight Bone Club", category: "Untote", file: "undead/wight_bone_club.png", artist: "Devin Night" },
  { key: "undead-wight-rusty-sword", labelDe: "Wiedergänger rostig Schwert", labelEn: "Wight Rusty Sword", category: "Untote", file: "undead/wight_rusty_sword.png", artist: "Devin Night" },
  { key: "undead-wight-shovel", labelDe: "Wiedergänger Schaufel", labelEn: "Wight Shovel", category: "Untote", file: "undead/wight_shovel.png", artist: "Devin Night" },
  { key: "undead-zombie-female-green", labelDe: "Zombie weiblich Grün", labelEn: "Zombie Female Green", category: "Untote", file: "undead/zombie_female_green.png", artist: "Devin Night" },
  { key: "undead-zombie-female-red", labelDe: "Zombie weiblich Rot", labelEn: "Zombie Female Red", category: "Untote", file: "undead/zombie_female_red.png", artist: "Devin Night" },
  { key: "undead-zombie-male-crawling", labelDe: "Zombie männlich kriechend", labelEn: "Zombie Male Crawling", category: "Untote", file: "undead/zombie_male_crawling.png", artist: "Devin Night" },
  { key: "undead-zombie-male-footdragging", labelDe: "Zombie männlich schleppend", labelEn: "Zombie Male Footdragging", category: "Untote", file: "undead/zombie_male_footdragging.png", artist: "Devin Night" },
  { key: "undead-zombie-male-grren", labelDe: "Zombie männlich Grün", labelEn: "Zombie Male Green", category: "Untote", file: "undead/zombie_male_grren.png", artist: "Devin Night" },
  { key: "undead-zombie-male-yellow", labelDe: "Zombie männlich Gelb", labelEn: "Zombie Male Yellow", category: "Untote", file: "undead/zombie_male_yellow.png", artist: "Devin Night" },
  { key: "undead-zombie-wolf", labelDe: "Zombie Wolf", labelEn: "Zombie Wolf", category: "Untote", file: "undead/zombie_wolf.png", artist: "Devin Night" },
  { key: "freebies-beetle-giant-01", labelDe: "Käfer Riese", labelEn: "Beetle Giant", category: "Verschiedenes", file: "freebies/Beetle_Giant_01.png", artist: "Devin Night" },
  { key: "freebies-bugbear-chieftan-10", labelDe: "Bugbear Häuptling", labelEn: "Bugbear Chieftan", category: "Verschiedenes", file: "freebies/Bugbear_Chieftan_10.png", artist: "Devin Night" },
  { key: "freebies-bugbear-mace-04", labelDe: "Bugbear Streitkolben", labelEn: "Bugbear Mace", category: "Verschiedenes", file: "freebies/Bugbear_Mace_04.png", artist: "Devin Night" },
  { key: "freebies-caveman-01", labelDe: "Höhlenmensch", labelEn: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_01.png", artist: "Devin Night" },
  { key: "freebies-caveman-02", labelDe: "Höhlenmensch", labelEn: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_02.png", artist: "Devin Night" },
  { key: "freebies-caveman-03", labelDe: "Höhlenmensch", labelEn: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_03.png", artist: "Devin Night" },
  { key: "freebies-caveman-08", labelDe: "Höhlenmensch", labelEn: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_08.png", artist: "Devin Night" },
  { key: "freebies-caveman-10", labelDe: "Höhlenmensch", labelEn: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_10.png", artist: "Devin Night" },
  { key: "freebies-caveman-11", labelDe: "Höhlenmensch", labelEn: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_11.png", artist: "Devin Night" },
  { key: "freebies-chaos-spawn-14", labelDe: "Chaos Brut", labelEn: "Chaos Spawn", category: "Verschiedenes", file: "freebies/Chaos_Spawn_14.png", artist: "Devin Night" },
  { key: "freebies-chaos-spawn-17", labelDe: "Chaos Brut", labelEn: "Chaos Spawn", category: "Verschiedenes", file: "freebies/Chaos_Spawn_17.png", artist: "Devin Night" },
  { key: "freebies-clockwork-slasher-13", labelDe: "Uhrwerk Schlitzer", labelEn: "Clockwork Slasher", category: "Verschiedenes", file: "freebies/Clockwork_Slasher_13.png", artist: "Devin Night" },
  { key: "freebies-demon-pit-15", labelDe: "Grubendämon", labelEn: "Demon Pit", category: "Verschiedenes", file: "freebies/Demon_Pit_15.png", artist: "Devin Night" },
  { key: "freebies-demon-slime-09", labelDe: "Dämon Schleim", labelEn: "Demon Slime", category: "Verschiedenes", file: "freebies/Demon_Slime_09.png", artist: "Devin Night" },
  { key: "freebies-dragon-green-14", labelDe: "Drache Grün", labelEn: "Dragon Green", category: "Verschiedenes", file: "freebies/Dragon_Green_14.png", artist: "Devin Night" },
  { key: "freebies-dragon-red-08", labelDe: "Drache Rot", labelEn: "Dragon Red", category: "Verschiedenes", file: "freebies/Dragon_Red_08.png", artist: "Devin Night" },
  { key: "freebies-dragonman-23", labelDe: "Drachenmensch", labelEn: "Dragonman", category: "Verschiedenes", file: "freebies/DragonMan_23.png", artist: "Devin Night" },
  { key: "freebies-evileye-06", labelDe: "Böses Auge", labelEn: "Evileye", category: "Verschiedenes", file: "freebies/EvilEye_06.png", artist: "Devin Night" },
  { key: "freebies-evileye-16", labelDe: "Böses Auge", labelEn: "Evileye", category: "Verschiedenes", file: "freebies/EvilEye_16.png", artist: "Devin Night" },
  { key: "freebies-frogmonster-07", labelDe: "Froschmonster", labelEn: "Frogmonster", category: "Verschiedenes", file: "freebies/Frogmonster_07.png", artist: "Devin Night" },
  { key: "freebies-giant-hill-16", labelDe: "Riese Hügel-", labelEn: "Giant Hill", category: "Verschiedenes", file: "freebies/Giant_Hill_16.png", artist: "Devin Night" },
  { key: "freebies-giantworm-18", labelDe: "Riesenwurm", labelEn: "Giantworm", category: "Verschiedenes", file: "freebies/GiantWorm_18.png", artist: "Devin Night" },
  { key: "freebies-grey-stalker-06", labelDe: "Grau Schleicher", labelEn: "Grey Stalker", category: "Verschiedenes", file: "freebies/Grey_Stalker_06.png", artist: "Devin Night" },
  { key: "freebies-grey-swordsman-13", labelDe: "Grau Schwertkämpfer", labelEn: "Grey Swordsman", category: "Verschiedenes", file: "freebies/Grey_Swordsman_13.png", artist: "Devin Night" },
  { key: "freebies-lavaman-12", labelDe: "Lavamann", labelEn: "Lavaman", category: "Verschiedenes", file: "freebies/Lavaman_12.png", artist: "Devin Night" },
  { key: "freebies-messenger-mounted-07", labelDe: "Bote beritten", labelEn: "Messenger Mounted", category: "Verschiedenes", file: "freebies/Messenger_Mounted_07.png", artist: "Devin Night" },
  { key: "freebies-polarbear-02", labelDe: "Eisbär", labelEn: "Polarbear", category: "Verschiedenes", file: "freebies/Polarbear_02.png", artist: "Devin Night" },
  { key: "freebies-rat-giant-05", labelDe: "Ratte Riese", labelEn: "Rat Giant", category: "Verschiedenes", file: "freebies/Rat_Giant_05.png", artist: "Devin Night" },
  { key: "freebies-wizard-evil-11", labelDe: "Magier böse", labelEn: "Wizard Evil", category: "Verschiedenes", file: "freebies/Wizard_Evil_11.png", artist: "Devin Night" },
  { key: "freebies-zombie-rotting-05", labelDe: "Zombie verwesend", labelEn: "Zombie Rotting", category: "Verschiedenes", file: "freebies/Zombie_Rotting_05.png", artist: "Devin Night" },
  { key: "freebies-zombie-rotting-12", labelDe: "Zombie verwesend", labelEn: "Zombie Rotting", category: "Verschiedenes", file: "freebies/Zombie_Rotting_12.png", artist: "Devin Night" },
  { key: "guards-nobles-human-alchemist-flasks-green", labelDe: "Mensch Alchemist Fläschchen Grün", labelEn: "Human Alchemist Flasks Green", category: "Wachen & Adlige", file: "guards-nobles/Human_Alchemist_Flasks_Green.png", artist: "Devin Night" },
  { key: "guards-nobles-human-alchemist-flasks-redfantasynoblenpctokenfree", labelDe: "Mensch Alchemist Fläschchen Rot", labelEn: "Human Alchemist Flasks Red", category: "Wachen & Adlige", file: "guards-nobles/Human_Alchemist_Flasks_Red[fantasy,noble,NPC,token,free].png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe", labelDe: "Mensch Wache Axt", labelEn: "Human Guard Axe", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-helmet", labelDe: "Mensch Wache Axt Helm", labelEn: "Human Guard Axe Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-helmet-2", labelDe: "Mensch Wache Axt Helm", labelEn: "Human Guard Axe Helmet-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Helmet-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-helmet-3", labelDe: "Mensch Wache Axt Helm", labelEn: "Human Guard Axe Helmet-3", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Helmet-3.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-purple", labelDe: "Mensch Wache Axt Lila", labelEn: "Human Guard Axe Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-purple-2", labelDe: "Mensch Wache Axt Lila", labelEn: "Human Guard Axe Purple-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Purple-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-purple-3", labelDe: "Mensch Wache Axt Lila", labelEn: "Human Guard Axe Purple-3", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Purple-3.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-2", labelDe: "Mensch Wache Axt", labelEn: "Human Guard Axe-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-3", labelDe: "Mensch Wache Axt", labelEn: "Human Guard Axe-3", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe-3.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-bow-helmet", labelDe: "Mensch Wache Bogen Helm", labelEn: "Human Guard Bow Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Bow_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-bow-purple", labelDe: "Mensch Wache Bogen Lila", labelEn: "Human Guard Bow Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Bow_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-helmet", labelDe: "Mensch Wache Armbrust Helm", labelEn: "Human Guard Crossbow Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-helmet-2", labelDe: "Mensch Wache Armbrust Helm", labelEn: "Human Guard Crossbow Helmet-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow_Helmet-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-purple", labelDe: "Mensch Wache Armbrust Lila", labelEn: "Human Guard Crossbow Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-purple-2", labelDe: "Mensch Wache Armbrust Lila", labelEn: "Human Guard Crossbow Purple-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow_Purple-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-2", labelDe: "Mensch Wache Armbrust", labelEn: "Human Guard Crossbow-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-shield-helmet", labelDe: "Mensch Wache Schild Helm", labelEn: "Human Guard Shield Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Shield_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-spear-purple", labelDe: "Mensch Wache Speer Lila", labelEn: "Human Guard Spear Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Spear_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-spear-shield", labelDe: "Mensch Wache Speer Schild", labelEn: "Human Guard Spear-shield", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Spear-Shield.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-spear-shield-helmet", labelDe: "Mensch Wache Speer Schild Helm", labelEn: "Human Guard Spear-shield Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Spear-Shield_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-spear-shield-purple", labelDe: "Mensch Wache Speer Schild Lila", labelEn: "Human Guard Spear-shield Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Spear-Shield_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-helmet", labelDe: "Mensch Wache Schwert Helm", labelEn: "Human Guard Sword Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-purple", labelDe: "Mensch Wache Schwert Lila", labelEn: "Human Guard Sword Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-helmet", labelDe: "Mensch Wache Schwert Schild Helm", labelEn: "Human Guard Sword-shield Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-helmet-2", labelDe: "Mensch Wache Schwert Schild Helm", labelEn: "Human Guard Sword-shield Helmet-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield_Helmet-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-purple", labelDe: "Mensch Wache Schwert Schild Lila", labelEn: "Human Guard Sword-shield Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-purple-2", labelDe: "Mensch Wache Schwert Schild Lila", labelEn: "Human Guard Sword-shield Purple-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield_Purple-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-2", labelDe: "Mensch Wache Schwert Schild", labelEn: "Human Guard Sword-shield-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-commander-helmet", labelDe: "Mensch Wachkommandant Helm", labelEn: "Human Guard-commander Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard-Commander_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-commander-purple", labelDe: "Mensch Wachkommandant Lila", labelEn: "Human Guard-commander Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard-Commander_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-commander-spear-purple", labelDe: "Mensch Wachkommandant Speer Lila", labelEn: "Human Guard-commander Spear Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard-commander_Spear_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-commander-sword-helmet", labelDe: "Mensch Wachkommandant Schwert Helm", labelEn: "Human Guard-commander Sword Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard-Commander_Sword_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-jester", labelDe: "Mensch Narr", labelEn: "Human Jester", category: "Wachen & Adlige", file: "guards-nobles/Human_Jester.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lady-blue", labelDe: "Mensch Lady Blau", labelEn: "Human Lady Blue", category: "Wachen & Adlige", file: "guards-nobles/Human_Lady_Blue.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lady-purple", labelDe: "Mensch Lady Lila", labelEn: "Human Lady Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Lady_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lady-sitting-pink", labelDe: "Mensch Lady sitzend Pink", labelEn: "Human Lady Sitting Pink", category: "Wachen & Adlige", file: "guards-nobles/Human_Lady_Sitting_Pink.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lady-sitting-purple", labelDe: "Mensch Lady sitzend Lila", labelEn: "Human Lady Sitting Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Lady_Sitting_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lord-purple", labelDe: "Mensch Lord Lila", labelEn: "Human Lord Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Lord_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lord-red", labelDe: "Mensch Lord Rot", labelEn: "Human Lord Red", category: "Wachen & Adlige", file: "guards-nobles/Human_Lord_Red.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lord-rod-purple", labelDe: "Mensch Lord Stab Lila", labelEn: "Human Lord Rod Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Lord_Rod_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lord-rogue-sword", labelDe: "Mensch Lord Schurke Schwert", labelEn: "Human Lord-rogue Sword", category: "Wachen & Adlige", file: "guards-nobles/Human_Lord-Rogue_Sword.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-bow-2fantasynoblenpctokenfree", labelDe: "Mensch Nomade Bogen", labelEn: "Human Nomad Bow-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Bow-2[fantasy,noble,NPC,token,free].png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-bowfantasynoblenpctokenfree", labelDe: "Mensch Nomade Bogen", labelEn: "Human Nomad Bow", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Bow[fantasy,noble,NPC,token,free].png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-scimitar-shield", labelDe: "Mensch Nomade Krummsäbel Schild", labelEn: "Human Nomad Scimitar-shield", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Scimitar-Shield.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-scimitar-shield-2", labelDe: "Mensch Nomade Krummsäbel Schild", labelEn: "Human Nomad Scimitar-shield-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Scimitar-Shield-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-scimitarfantasynoblenpctokenfree", labelDe: "Mensch Nomade Krummsäbel", labelEn: "Human Nomad Scimitar", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Scimitar[fantasy,noble,NPC,token,free].png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-scimitars", labelDe: "Mensch Nomade Krummsäbel", labelEn: "Human Nomad Scimitars", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Scimitars.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-spear", labelDe: "Mensch Nomade Speer", labelEn: "Human Nomad Spear", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Spear.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-spear-shield", labelDe: "Mensch Nomade Speer Schild", labelEn: "Human Nomad Spear-shield", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Spear-Shield.png", artist: "Devin Night" },
  { key: "guards-nobles-human-witch-black", labelDe: "Mensch Hexe Schwarz", labelEn: "Human Witch Black", category: "Wachen & Adlige", file: "guards-nobles/Human_Witch_Black.png", artist: "Devin Night" },
  { key: "guards-nobles-human-witch-blue", labelDe: "Mensch Hexe Blau", labelEn: "Human Witch Blue", category: "Wachen & Adlige", file: "guards-nobles/Human_Witch_Blue.png", artist: "Devin Night" },
  { key: "guards-nobles-human-witch-green", labelDe: "Mensch Hexe Grün", labelEn: "Human Witch Green", category: "Wachen & Adlige", file: "guards-nobles/Human_Witch_Green.png", artist: "Devin Night" },
  { key: "guards-nobles-human-witch-staff-red", labelDe: "Mensch Hexe Stab Rot", labelEn: "Human Witch Staff Red", category: "Wachen & Adlige", file: "guards-nobles/Human_Witch_Staff_Red.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-axe-shield", labelDe: "Zwerg weiblich Axt Schild", labelEn: "Dwarf Female Axe Shield", category: "Zwerge", file: "dwarves/dwarf_female_axe_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-axe-shield-2", labelDe: "Zwerg weiblich Axt Schild", labelEn: "Dwarf Female Axe Shield", category: "Zwerge", file: "dwarves/dwarf_female_axe_shield_2.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-fighter-axe", labelDe: "Zwerg weiblich Krieger Axt", labelEn: "Dwarf Female Fighter Axe", category: "Zwerge", file: "dwarves/dwarf_female_fighter_axe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-hammer-shield", labelDe: "Zwerg weiblich Hammer Schild", labelEn: "Dwarf Female Hammer Shield", category: "Zwerge", file: "dwarves/dwarf_female_hammer_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-pick-plate", labelDe: "Zwerg weiblich Spitzhacke Plattenrüstung", labelEn: "Dwarf Female Pick Plate", category: "Zwerge", file: "dwarves/dwarf_female_pick_plate.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-spear", labelDe: "Zwerg weiblich Speer", labelEn: "Dwarf Female Spear", category: "Zwerge", file: "dwarves/dwarf_female_spear.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-axe-shield-2", labelDe: "Zwerg männlich Axt Schild", labelEn: "Dwarf Male Axe Shield", category: "Zwerge", file: "dwarves/dwarf_male_axe_shield_2.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-axe-shield-gold", labelDe: "Zwerg männlich Axt Schild Gold", labelEn: "Dwarf Male Axe Shield Gold", category: "Zwerge", file: "dwarves/dwarf_male_axe_shield_gold.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-axe-shield-green", labelDe: "Zwerg männlich Axt Schild Grün", labelEn: "Dwarf Male Axe Shield Green", category: "Zwerge", file: "dwarves/dwarf_male_axe_shield_green.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-axe-shield-silver", labelDe: "Zwerg männlich Axt Schild Silber", labelEn: "Dwarf Male Axe Shield Silver", category: "Zwerge", file: "dwarves/dwarf_male_axe_shield_silver.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-blunderbus-canon", labelDe: "Zwerg männlich Donnerbüchse Kanone", labelEn: "Dwarf Male Blunderbus Cannon", category: "Zwerge", file: "dwarves/dwarf_male_blunderbus_canon.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-brawler", labelDe: "Zwerg männlich Raufbold", labelEn: "Dwarf Male Brawler", category: "Zwerge", file: "dwarves/dwarf_male_brawler.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-cleric-yellow", labelDe: "Zwerg männlich Kleriker Gelb", labelEn: "Dwarf Male Cleric Yellow", category: "Zwerge", file: "dwarves/dwarf_male_cleric_yellow.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-copper-hammer", labelDe: "Zwerg männlich Kupfer Hammer", labelEn: "Dwarf Male Copper Hammer", category: "Zwerge", file: "dwarves/dwarf_male_copper_hammer.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-crossbow-2", labelDe: "Zwerg männlich Armbrust", labelEn: "Dwarf Male Crossbow", category: "Zwerge", file: "dwarves/dwarf_male_crossbow_2.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-crossbow-red", labelDe: "Zwerg männlich Armbrust Rot", labelEn: "Dwarf Male Crossbow Red", category: "Zwerge", file: "dwarves/dwarf_male_crossbow_red.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-crosswbow-green-3", labelDe: "Zwerg männlich Armbrust Grün", labelEn: "Dwarf Male Crossbow Green", category: "Zwerge", file: "dwarves/dwarf_male_crosswbow_green_3.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-doubleaxe", labelDe: "Zwerg männlich Doppelaxt", labelEn: "Dwarf Male Doubleaxe", category: "Zwerge", file: "dwarves/dwarf_male_doubleaxe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-doubleaxe-shield", labelDe: "Zwerg männlich Doppelaxt Schild", labelEn: "Dwarf Male Doubleaxe Shield", category: "Zwerge", file: "dwarves/dwarf_male_doubleaxe_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-doubleaxe-shield-mail", labelDe: "Zwerg männlich Doppelaxt Schild Kettenhemd", labelEn: "Dwarf Male Doubleaxe Shield Mail", category: "Zwerge", file: "dwarves/dwarf_male_doubleaxe_shield_mail.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-fighter-mace", labelDe: "Zwerg männlich Krieger Streitkolben", labelEn: "Dwarf Male Fighter Mace", category: "Zwerge", file: "dwarves/dwarf_male_fighter_mace.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-fighter-mage", labelDe: "Zwerg männlich Krieger Magier", labelEn: "Dwarf Male Fighter Mage", category: "Zwerge", file: "dwarves/dwarf_male_fighter_mage.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-fighter-scythe", labelDe: "Zwerg männlich Krieger Sense", labelEn: "Dwarf Male Fighter Scythe", category: "Zwerge", file: "dwarves/dwarf_male_fighter_scythe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-flag-standard", labelDe: "Zwerg männlich Fahne Standarte", labelEn: "Dwarf Male Flag Standard", category: "Zwerge", file: "dwarves/dwarf_male_flag_standard.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-hammer-shield", labelDe: "Zwerg männlich Hammer Schild", labelEn: "Dwarf Male Hammer Shield", category: "Zwerge", file: "dwarves/dwarf_male_hammer_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-hammer-shield-green", labelDe: "Zwerg männlich Hammer Schild Grün", labelEn: "Dwarf Male Hammer Shield Green", category: "Zwerge", file: "dwarves/dwarf_male_hammer_shield_green.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-handaxes-red", labelDe: "Zwerg männlich Handäxte Rot", labelEn: "Dwarf Male Handaxes Red", category: "Zwerge", file: "dwarves/dwarf_male_handaxes_red.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-mace-hammer-red", labelDe: "Zwerg männlich Streitkolben Hammer Rot", labelEn: "Dwarf Male Mace Hammer Red", category: "Zwerge", file: "dwarves/dwarf_male_mace_hammer_red.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-monk", labelDe: "Zwerg männlich Mönch", labelEn: "Dwarf Male Monk", category: "Zwerge", file: "dwarves/dwarf_male_monk.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-pale-axe", labelDe: "Zwerg männlich Blass Axt", labelEn: "Dwarf Male Pale Axe", category: "Zwerge", file: "dwarves/dwarf_male_pale_axe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-pick-shield", labelDe: "Zwerg männlich Spitzhacke Schild", labelEn: "Dwarf Male Pick Shield", category: "Zwerge", file: "dwarves/dwarf_male_pick_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-plate-flail-shield", labelDe: "Zwerg männlich Plattenrüstung Kriegsflegel Schild", labelEn: "Dwarf Male Plate Flail Shield", category: "Zwerge", file: "dwarves/dwarf_male_plate_flail_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-plate-hammer-shield", labelDe: "Zwerg männlich Plattenrüstung Hammer Schild", labelEn: "Dwarf Male Plate Hammer Shield", category: "Zwerge", file: "dwarves/dwarf_male_plate_hammer_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-poleaxe", labelDe: "Zwerg männlich Stangenaxt", labelEn: "Dwarf Male Poleaxe", category: "Zwerge", file: "dwarves/dwarf_male_poleaxe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-priest-longhammer", labelDe: "Zwerg männlich Priester Langhammer", labelEn: "Dwarf Male Priest Longhammer", category: "Zwerge", file: "dwarves/dwarf_male_priest_longhammer.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-red-priest", labelDe: "Zwerg männlich Rot Priester", labelEn: "Dwarf Male Red Priest", category: "Zwerge", file: "dwarves/dwarf_male_red_priest.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-shield-axe", labelDe: "Zwerg männlich Schild Axt", labelEn: "Dwarf Male Shield Axe", category: "Zwerge", file: "dwarves/dwarf_male_shield_axe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-spear", labelDe: "Zwerg männlich Speer", labelEn: "Dwarf Male Spear", category: "Zwerge", file: "dwarves/dwarf_male_spear.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-spear-blue", labelDe: "Zwerg männlich Speer Blau", labelEn: "Dwarf Male Spear Blue", category: "Zwerge", file: "dwarves/dwarf_male_spear_blue.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-spear-green", labelDe: "Zwerg männlich Speer Grün", labelEn: "Dwarf Male Spear Green", category: "Zwerge", file: "dwarves/dwarf_male_spear_green.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-swords", labelDe: "Zwerg männlich Schwerter", labelEn: "Dwarf Male Swords", category: "Zwerge", file: "dwarves/dwarf_male_swords.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-thief-dagger", labelDe: "Zwerg männlich Dieb Dolch", labelEn: "Dwarf Male Thief Dagger", category: "Zwerge", file: "dwarves/dwarf_male_thief_dagger.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-thief-flail", labelDe: "Zwerg männlich Dieb Kriegsflegel", labelEn: "Dwarf Male Thief Flail", category: "Zwerge", file: "dwarves/dwarf_male_thief_flail.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-thief-longaxe", labelDe: "Zwerg männlich Dieb Langaxt", labelEn: "Dwarf Male Thief Longaxe", category: "Zwerge", file: "dwarves/dwarf_male_thief_longaxe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-veteran-spear-shield", labelDe: "Zwerg männlich Veteran Speer Schild", labelEn: "Dwarf Male Veteran Spear Shield", category: "Zwerge", file: "dwarves/dwarf_male_veteran_spear_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-warhammer", labelDe: "Zwerg männlich Kriegshammer", labelEn: "Dwarf Male Warhammer", category: "Zwerge", file: "dwarves/dwarf_male_warhammer.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-wizard", labelDe: "Zwerg männlich Magier", labelEn: "Dwarf Male Wizard", category: "Zwerge", file: "dwarves/dwarf_male_wizard.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-wizard-staff", labelDe: "Zwerg männlich Magier Stab", labelEn: "Dwarf Male Wizard Staff", category: "Zwerge", file: "dwarves/dwarf_male_wizard_staff.png", artist: "Devin Night" },
];

export const TOKEN_ICON_BY_KEY: Record<string, TokenIcon> = Object.fromEntries(
  TOKEN_ICONS.map((i) => [i.key, i]),
);

export const TOKEN_ICON_CATEGORIES: string[] = [...new Set(TOKEN_ICONS.map((i) => i.category))];
