// Curated selection of Devin Night's free VTT token art (TP000-TP020 free
// packs), for the marker/monster token icon picker -- see TODO.md "VTT icon
// picker for marker/monster/NPC tokens". Images live as static files under
// client/public/tokens/, same split as shared/src/boardTiles.ts's
// TILE_MATERIALS (data here, art on disk, no DB/upload involved). Generated
// from what actually shipped in the free bundle -- do not hand-edit `file`
// paths without also touching the file on disk.
//
// Licensing: free for personal/gaming-group use per Devin Night's own terms
// (https://filedn.com/lV1TH8uSVwALfJxGuEcQJX0/TokenUsage.html) -- that page
// also asks to be contacted first, which is being done separately. Credit
// "Devin Night" belongs wherever the app ends up crediting its art sources.
//
// `label` is currently the English source filename, prettified -- a German
// pass is a follow-up (pure data edit here, no code/schema change needed).

export interface TokenIcon {
  /** Stable slug stored on BoardToken.iconAsset -- never the filename. */
  key: string;
  label: string;
  /** Picker category tab. */
  category: string;
  /** Path under client/public/tokens/. */
  file: string;
  artist: string;
}

export const TOKEN_ICONS: TokenIcon[] = [
  { key: "characters-adventurer-dead-22", label: "Adventurer Dead", category: "Charaktere", file: "characters/Adventurer_Dead_22.png", artist: "Devin Night" },
  { key: "characters-adventurer-dead-28", label: "Adventurer Dead", category: "Charaktere", file: "characters/Adventurer_Dead_28.png", artist: "Devin Night" },
  { key: "characters-adventurer-dead-32", label: "Adventurer Dead", category: "Charaktere", file: "characters/Adventurer_Dead_32.png", artist: "Devin Night" },
  { key: "characters-archer-40", label: "Archer", category: "Charaktere", file: "characters/Archer_40.png", artist: "Devin Night" },
  { key: "characters-cleric-blue-48", label: "Cleric Blue", category: "Charaktere", file: "characters/Cleric_Blue_48.png", artist: "Devin Night" },
  { key: "characters-cleric-red-47", label: "Cleric Red", category: "Charaktere", file: "characters/Cleric_Red_47.png", artist: "Devin Night" },
  { key: "characters-dwarven-fighter-hammer-03", label: "Dwarven Fighter Hammer", category: "Charaktere", file: "characters/Dwarven_fighter_hammer_03.png", artist: "Devin Night" },
  { key: "characters-elven-blue-fighter-09", label: "Elven Blue Fighter", category: "Charaktere", file: "characters/Elven_Blue_fighter_09.png", artist: "Devin Night" },
  { key: "characters-elven-green-archer-02", label: "Elven Green Archer", category: "Charaktere", file: "characters/Elven_Green_Archer_02.png", artist: "Devin Night" },
  { key: "characters-fighter-36", label: "Fighter", category: "Charaktere", file: "characters/Fighter_36.png", artist: "Devin Night" },
  { key: "characters-fighter-39", label: "Fighter", category: "Charaktere", file: "characters/Fighter_39.png", artist: "Devin Night" },
  { key: "characters-fighter-45", label: "Fighter", category: "Charaktere", file: "characters/Fighter_45.png", artist: "Devin Night" },
  { key: "characters-fighter-blue-07", label: "Fighter Blue", category: "Charaktere", file: "characters/Fighter_blue_07.png", artist: "Devin Night" },
  { key: "characters-fighter-blue-female-06", label: "Fighter Blue Female", category: "Charaktere", file: "characters/Fighter_Blue_Female_06.png", artist: "Devin Night" },
  { key: "characters-fighter-blue-spear-30", label: "Fighter Blue Spear", category: "Charaktere", file: "characters/Fighter_Blue_Spear_30.png", artist: "Devin Night" },
  { key: "characters-fighter-blue-sword-26", label: "Fighter Blue Sword", category: "Charaktere", file: "characters/Fighter_Blue_Sword_26.png", artist: "Devin Night" },
  { key: "characters-fighter-female-35", label: "Fighter Female", category: "Charaktere", file: "characters/Fighter_Female_35.png", artist: "Devin Night" },
  { key: "characters-fighter-female-dagger-34", label: "Fighter Female Dagger", category: "Charaktere", file: "characters/Fighter_Female_Dagger_34.png", artist: "Devin Night" },
  { key: "characters-fighter-gold-11", label: "Fighter Gold", category: "Charaktere", file: "characters/Fighter_Gold_11.png", artist: "Devin Night" },
  { key: "characters-fighter-green-15", label: "Fighter Green", category: "Charaktere", file: "characters/Fighter_Green_15.png", artist: "Devin Night" },
  { key: "characters-fighter-mace-24", label: "Fighter Mace", category: "Charaktere", file: "characters/Fighter_Mace_24.png", artist: "Devin Night" },
  { key: "characters-fighter-metal-18", label: "Fighter Metal", category: "Charaktere", file: "characters/Fighter_Metal_18.png", artist: "Devin Night" },
  { key: "characters-fighter-silver-10", label: "Fighter Silver", category: "Charaktere", file: "characters/Fighter_Silver_10.png", artist: "Devin Night" },
  { key: "characters-fighter-spear-purple-29", label: "Fighter Spear Purple", category: "Charaktere", file: "characters/Fighter_Spear_Purple_29.png", artist: "Devin Night" },
  { key: "characters-fighter-sword-25", label: "Fighter Sword", category: "Charaktere", file: "characters/Fighter_Sword_25.png", artist: "Devin Night" },
  { key: "characters-fighter-sword-buckler-31", label: "Fighter Sword Buckler", category: "Charaktere", file: "characters/Fighter_Sword_Buckler_31.png", artist: "Devin Night" },
  { key: "characters-halfling-05", label: "Halfling", category: "Charaktere", file: "characters/Halfling_05.png", artist: "Devin Night" },
  { key: "characters-halfling-fighter-41", label: "Halfling Fighter", category: "Charaktere", file: "characters/Halfling_fighter_41.png", artist: "Devin Night" },
  { key: "characters-knight-49", label: "Knight", category: "Charaktere", file: "characters/Knight_49.png", artist: "Devin Night" },
  { key: "characters-magicuser-01", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_01.png", artist: "Devin Night" },
  { key: "characters-magicuser-16", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_16.png", artist: "Devin Night" },
  { key: "characters-magicuser-17", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_17.png", artist: "Devin Night" },
  { key: "characters-magicuser-19", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_19.png", artist: "Devin Night" },
  { key: "characters-magicuser-27", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_27.png", artist: "Devin Night" },
  { key: "characters-magicuser-37", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_37.png", artist: "Devin Night" },
  { key: "characters-magicuser-38", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_38.png", artist: "Devin Night" },
  { key: "characters-magicuser-43", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_43.png", artist: "Devin Night" },
  { key: "characters-magicuser-44", label: "Magicuser", category: "Charaktere", file: "characters/Magicuser_44.png", artist: "Devin Night" },
  { key: "characters-magicuser-green-08", label: "Magicuser Green", category: "Charaktere", file: "characters/Magicuser_Green_08.png", artist: "Devin Night" },
  { key: "characters-thief-14", label: "Thief", category: "Charaktere", file: "characters/Thief_14.png", artist: "Devin Night" },
  { key: "characters-thief-daggers-21", label: "Thief Daggers", category: "Charaktere", file: "characters/Thief_Daggers_21.png", artist: "Devin Night" },
  { key: "characters-villager-female-04", label: "Villager Female", category: "Charaktere", file: "characters/Villager_Female_04.png", artist: "Devin Night" },
  { key: "characters-whipper-50", label: "Whipper", category: "Charaktere", file: "characters/Whipper_50.png", artist: "Devin Night" },
  { key: "characters-2-car-warrior-sword-sword", label: "Car Warrior Sword-sword", category: "Charaktere II", file: "characters-2/Car_Warrior_Sword-Sword.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-barbarian-axe", label: "Dwarf Barbarian Axe", category: "Charaktere II", file: "characters-2/Dwarf_Barbarian_Axe.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-cleric-morningstar", label: "Dwarf Cleric Morningstar", category: "Charaktere II", file: "characters-2/Dwarf_Cleric_Morningstar.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-monk-fist", label: "Dwarf Monk Fist", category: "Charaktere II", file: "characters-2/Dwarf_Monk_Fist.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-warrior-axe-plate", label: "Dwarf Warrior Axe Plate", category: "Charaktere II", file: "characters-2/Dwarf_warrior_Axe_Plate.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-warrior-crossbow-leather", label: "Dwarf Warrior Crossbow Leather", category: "Charaktere II", file: "characters-2/Dwarf_Warrior_Crossbow_Leather.png", artist: "Devin Night" },
  { key: "characters-2-dwarf-warrior-mace", label: "Dwarf Warrior Mace", category: "Charaktere II", file: "characters-2/Dwarf_Warrior_Mace.png", artist: "Devin Night" },
  { key: "characters-2-elf-druid-sickle", label: "Elf Druid Sickle", category: "Charaktere II", file: "characters-2/Elf_Druid_Sickle.png", artist: "Devin Night" },
  { key: "characters-2-elf-druid-sickle-leather", label: "Elf Druid Sickle Leather", category: "Charaktere II", file: "characters-2/Elf_Druid_Sickle_Leather.png", artist: "Devin Night" },
  { key: "characters-2-elf-monk-fist", label: "Elf Monk Fist", category: "Charaktere II", file: "characters-2/Elf_Monk_Fist.png", artist: "Devin Night" },
  { key: "characters-2-elf-monk-fist-2", label: "Elf Monk Fist-2", category: "Charaktere II", file: "characters-2/Elf_Monk_Fist-2.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-bow", label: "Elf Rogue Bow", category: "Charaktere II", file: "characters-2/Elf_Rogue_Bow.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-crossbow", label: "Elf Rogue Crossbow", category: "Charaktere II", file: "characters-2/Elf_Rogue_Crossbow.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-crossbow-spell", label: "Elf Rogue Crossbow-spell", category: "Charaktere II", file: "characters-2/Elf_Rogue_Crossbow-Spell.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-sword-crossbow", label: "Elf Rogue Sword-crossbow", category: "Charaktere II", file: "characters-2/Elf_Rogue_Sword-Crossbow.png", artist: "Devin Night" },
  { key: "characters-2-elf-rogue-two-swords", label: "Elf Rogue Two-swords", category: "Charaktere II", file: "characters-2/Elf_Rogue_two-swords.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-sword", label: "Elf Warrior Sword", category: "Charaktere II", file: "characters-2/Elf_Warrior_Sword.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-sword-shield", label: "Elf Warrior Sword-shield", category: "Charaktere II", file: "characters-2/Elf_Warrior_Sword-Shield.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow", label: "Elf Warrior-archer Bow", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather", label: "Elf Warrior-archer Bow Leather", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather-2", label: "Elf Warrior-archer Bow Leather-2", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather-2.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather-3", label: "Elf Warrior-archer Bow Leather-3", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather-3.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather-4", label: "Elf Warrior-archer Bow Leather-4", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather-4.png", artist: "Devin Night" },
  { key: "characters-2-elf-warrior-archer-bow-leather-5", label: "Elf Warrior-archer Bow Leather-5", category: "Charaktere II", file: "characters-2/Elf_Warrior-Archer_Bow_Leather-5.png", artist: "Devin Night" },
  { key: "characters-2-gnome-warrior-sword-shield", label: "Gnome Warrior Sword-shield", category: "Charaktere II", file: "characters-2/Gnome_Warrior_Sword-Shield.png", artist: "Devin Night" },
  { key: "characters-2-half-elf-wizard-staff", label: "Half-elf Wizard Staff", category: "Charaktere II", file: "characters-2/Half-elf_Wizard_Staff.png", artist: "Devin Night" },
  { key: "characters-2-half-orc-warrior-hammer-mace", label: "Half-orc Warrior Hammer-mace", category: "Charaktere II", file: "characters-2/Half-Orc_Warrior_Hammer-Mace.png", artist: "Devin Night" },
  { key: "characters-2-half-orc-warrior-polearm", label: "Half-orc Warrior Polearm", category: "Charaktere II", file: "characters-2/Half-Orc_Warrior_PoleArm.png", artist: "Devin Night" },
  { key: "characters-2-half-orc-warrior-polearm-shield", label: "Half-orc Warrior Polearm-shield", category: "Charaktere II", file: "characters-2/Half-Orc_Warrior_PoleArm-Shield.png", artist: "Devin Night" },
  { key: "characters-2-half-orc-warrior-sword", label: "Half-orc Warrior Sword", category: "Charaktere II", file: "characters-2/Half-Orc_Warrior_Sword.png", artist: "Devin Night" },
  { key: "characters-2-halfling-rogue-daggers", label: "Halfling Rogue Daggers", category: "Charaktere II", file: "characters-2/Halfling_Rogue_Daggers.png", artist: "Devin Night" },
  { key: "characters-2-human-barbarian-claws", label: "Human Barbarian Claws", category: "Charaktere II", file: "characters-2/Human_Barbarian_Claws.png", artist: "Devin Night" },
  { key: "characters-2-human-barbarian-sword-shield", label: "Human Barbarian Sword-shield", category: "Charaktere II", file: "characters-2/Human_Barbarian_Sword-Shield.png", artist: "Devin Night" },
  { key: "characters-2-human-cleric-flail-shield-plate", label: "Human Cleric Flail-shield Plate", category: "Charaktere II", file: "characters-2/Human_Cleric_Flail-Shield_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-cleric-holysymbol-shield-plate", label: "Human Cleric Holysymbol-shield Plate", category: "Charaktere II", file: "characters-2/Human_Cleric_HolySymbol-Shield_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-cleric-mace-shield-plate", label: "Human Cleric Mace-shield Plate", category: "Charaktere II", file: "characters-2/Human_Cleric_Mace-Shield_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-mage", label: "Human Mage", category: "Charaktere II", file: "characters-2/Human_Mage.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-masked", label: "Human Mage Masked", category: "Charaktere II", file: "characters-2/Human_Mage_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff", label: "Human Mage Staff", category: "Charaktere II", file: "characters-2/Human_Mage_Staff.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-masked", label: "Human Mage Staff Masked", category: "Charaktere II", file: "characters-2/Human_Mage_Staff_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-2", label: "Human Mage Staff-2", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-2.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-3", label: "Human Mage Staff-3", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-3.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-4", label: "Human Mage Staff-4", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-4.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-5", label: "Human Mage Staff-5", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-5.png", artist: "Devin Night" },
  { key: "characters-2-human-mage-staff-6", label: "Human Mage Staff-6", category: "Charaktere II", file: "characters-2/Human_Mage_Staff-6.png", artist: "Devin Night" },
  { key: "characters-2-human-rogue-crossbow", label: "Human Rogue Crossbow", category: "Charaktere II", file: "characters-2/Human_Rogue_Crossbow.png", artist: "Devin Night" },
  { key: "characters-2-human-rogue-rapier-crossbow", label: "Human Rogue Rapier-crossbow", category: "Charaktere II", file: "characters-2/Human_Rogue_Rapier-Crossbow.png", artist: "Devin Night" },
  { key: "characters-2-human-rogue-rapier-dagger", label: "Human Rogue Rapier-dagger", category: "Charaktere II", file: "characters-2/Human_Rogue_Rapier-Dagger.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-polearm", label: "Human Warrior Polearm", category: "Charaktere II", file: "characters-2/Human_Warrior_Polearm.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-spear-masked", label: "Human Warrior Spear Masked", category: "Charaktere II", file: "characters-2/Human_Warrior_Spear_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-staff-masked", label: "Human Warrior Staff Masked", category: "Charaktere II", file: "characters-2/Human_Warrior_Staff_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-masked", label: "Human Warrior Sword Masked", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword_Masked.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-plate", label: "Human Warrior Sword Plate", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield", label: "Human Warrior Sword-shield", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield-plate", label: "Human Warrior Sword-shield Plate", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield_Plate.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield-plate-2", label: "Human Warrior Sword-shield Plate-2", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield_Plate-2.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield-plate-3", label: "Human Warrior Sword-shield Plate-3", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield_Plate-3.png", artist: "Devin Night" },
  { key: "characters-2-human-warrior-sword-shield-2", label: "Human Warrior Sword-shield-2", category: "Charaktere II", file: "characters-2/Human_Warrior_Sword-Shield-2.png", artist: "Devin Night" },
  { key: "characters-2-human-witch-book", label: "Human Witch Book", category: "Charaktere II", file: "characters-2/Human_Witch_Book.png", artist: "Devin Night" },
  { key: "characters-2-thief-rogue-daggers", label: "Thief Rogue Daggers", category: "Charaktere II", file: "characters-2/Thief_Rogue_Daggers.png", artist: "Devin Night" },
  { key: "characters-2-thief-rogue-sword", label: "Thief Rogue Sword", category: "Charaktere II", file: "characters-2/Thief_Rogue_Sword.png", artist: "Devin Night" },
  { key: "werecreatures-bear-22", label: "Bear", category: "Gestaltwandler", file: "werecreatures/bear_22.png", artist: "Devin Night" },
  { key: "werecreatures-bear-24", label: "Bear", category: "Gestaltwandler", file: "werecreatures/bear_24.png", artist: "Devin Night" },
  { key: "werecreatures-boar-04", label: "Boar", category: "Gestaltwandler", file: "werecreatures/boar_04.png", artist: "Devin Night" },
  { key: "werecreatures-boar-10", label: "Boar", category: "Gestaltwandler", file: "werecreatures/boar_10.png", artist: "Devin Night" },
  { key: "werecreatures-boar-16", label: "Boar", category: "Gestaltwandler", file: "werecreatures/boar_16.png", artist: "Devin Night" },
  { key: "werecreatures-boar-17", label: "Boar", category: "Gestaltwandler", file: "werecreatures/boar_17.png", artist: "Devin Night" },
  { key: "werecreatures-rat-07", label: "Rat", category: "Gestaltwandler", file: "werecreatures/rat_07.png", artist: "Devin Night" },
  { key: "werecreatures-rat-11", label: "Rat", category: "Gestaltwandler", file: "werecreatures/rat_11.png", artist: "Devin Night" },
  { key: "werecreatures-rat-32", label: "Rat", category: "Gestaltwandler", file: "werecreatures/rat_32.png", artist: "Devin Night" },
  { key: "werecreatures-rat-swarm", label: "Rat Swarm", category: "Gestaltwandler", file: "werecreatures/rat_swarm.png", artist: "Devin Night" },
  { key: "werecreatures-servant", label: "Servant", category: "Gestaltwandler", file: "werecreatures/servant.png", artist: "Devin Night" },
  { key: "werecreatures-tiger-27", label: "Tiger", category: "Gestaltwandler", file: "werecreatures/tiger_27.png", artist: "Devin Night" },
  { key: "werecreatures-tiger-dark-28", label: "Tiger Dark", category: "Gestaltwandler", file: "werecreatures/tiger_dark_28.png", artist: "Devin Night" },
  { key: "werecreatures-victim-female-33", label: "Victim Female", category: "Gestaltwandler", file: "werecreatures/victim_female_33.png", artist: "Devin Night" },
  { key: "werecreatures-victim-female-34", label: "Victim Female", category: "Gestaltwandler", file: "werecreatures/victim_female_34.png", artist: "Devin Night" },
  { key: "werecreatures-victim-male-29", label: "Victim Male", category: "Gestaltwandler", file: "werecreatures/victim_male_29.png", artist: "Devin Night" },
  { key: "werecreatures-victim-male-30", label: "Victim Male", category: "Gestaltwandler", file: "werecreatures/victim_male_30.png", artist: "Devin Night" },
  { key: "werecreatures-victim-male-31", label: "Victim Male", category: "Gestaltwandler", file: "werecreatures/victim_male_31.png", artist: "Devin Night" },
  { key: "werecreatures-victim-male-35", label: "Victim Male", category: "Gestaltwandler", file: "werecreatures/victim_male_35.png", artist: "Devin Night" },
  { key: "werecreatures-werebear-20", label: "Werebear", category: "Gestaltwandler", file: "werecreatures/werebear_20.png", artist: "Devin Night" },
  { key: "werecreatures-werebear-21", label: "Werebear", category: "Gestaltwandler", file: "werecreatures/werebear_21.png", artist: "Devin Night" },
  { key: "werecreatures-werebear-25", label: "Werebear", category: "Gestaltwandler", file: "werecreatures/werebear_25.png", artist: "Devin Night" },
  { key: "werecreatures-wereboar-15", label: "Wereboar", category: "Gestaltwandler", file: "werecreatures/wereboar_15.png", artist: "Devin Night" },
  { key: "werecreatures-wereboar-fighter-09", label: "Wereboar Fighter", category: "Gestaltwandler", file: "werecreatures/wereboar_fighter_09.png", artist: "Devin Night" },
  { key: "werecreatures-wererat-03", label: "Wererat", category: "Gestaltwandler", file: "werecreatures/wererat_03.png", artist: "Devin Night" },
  { key: "werecreatures-wererat-05", label: "Wererat", category: "Gestaltwandler", file: "werecreatures/wererat_05.png", artist: "Devin Night" },
  { key: "werecreatures-wererat-06", label: "Wererat", category: "Gestaltwandler", file: "werecreatures/wererat_06.png", artist: "Devin Night" },
  { key: "werecreatures-wererat-fighter-08", label: "Wererat Fighter", category: "Gestaltwandler", file: "werecreatures/wererat_fighter_08.png", artist: "Devin Night" },
  { key: "werecreatures-weretiger-23", label: "Weretiger", category: "Gestaltwandler", file: "werecreatures/weretiger_23.png", artist: "Devin Night" },
  { key: "werecreatures-weretiger-26", label: "Weretiger", category: "Gestaltwandler", file: "werecreatures/weretiger_26.png", artist: "Devin Night" },
  { key: "werecreatures-werewolf-12", label: "Werewolf", category: "Gestaltwandler", file: "werecreatures/werewolf_12.png", artist: "Devin Night" },
  { key: "werecreatures-werewolf-13", label: "Werewolf", category: "Gestaltwandler", file: "werecreatures/werewolf_13.png", artist: "Devin Night" },
  { key: "werecreatures-werewolf-fighter-14", label: "Werewolf Fighter", category: "Gestaltwandler", file: "werecreatures/werewolf_fighter_14.png", artist: "Devin Night" },
  { key: "werecreatures-wolf-18", label: "Wolf", category: "Gestaltwandler", file: "werecreatures/wolf_18.png", artist: "Devin Night" },
  { key: "werecreatures-wolf-19", label: "Wolf", category: "Gestaltwandler", file: "werecreatures/wolf_19.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-archer", label: "Goblin Archer", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_archer.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-archer2", label: "Goblin Archer2", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_archer2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-axeman", label: "Goblin Axeman", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_axeman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-crossbow", label: "Goblin Crossbow", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_crossbow.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-crossbow2", label: "Goblin Crossbow2", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_crossbow2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-crossbow3", label: "Goblin Crossbow3", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_crossbow3.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-crossbow4", label: "Goblin Crossbow4", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_crossbow4.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-daggers", label: "Goblin Daggers", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_daggers.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-dead-33", label: "Goblin Dead", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_dead_33.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-dead-34", label: "Goblin Dead", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_dead_34.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-fighter", label: "Goblin Fighter", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_fighter.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-mace", label: "Goblin Mace", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_mace.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-shaman", label: "Goblin Shaman", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_shaman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-shaman2", label: "Goblin Shaman2", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_shaman2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-shaman3", label: "Goblin Shaman3", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_shaman3.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-shaman4", label: "Goblin Shaman4", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_shaman4.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-spearman", label: "Goblin Spearman", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_spearman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-goblin-swordsman", label: "Goblin Swordsman", category: "Goblins & Kobolde", file: "goblins-kobolds/goblin_swordsman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-archer", label: "Kobold Archer", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_archer.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-dead-06", label: "Kobold Dead", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_dead_06.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-dead-12", label: "Kobold Dead", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_dead_12.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter", label: "Kobold Fighter", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter2", label: "Kobold Fighter2", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter3", label: "Kobold Fighter3", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter3.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter4", label: "Kobold Fighter4", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter4.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-fighter5", label: "Kobold Fighter5", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_fighter5.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-shaman1", label: "Kobold Shaman1", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_shaman1.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-shaman2", label: "Kobold Shaman2", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_shaman2.png", artist: "Devin Night" },
  { key: "goblins-kobolds-kobold-spearman", label: "Kobold Spearman", category: "Goblins & Kobolde", file: "goblins-kobolds/kobold_spearman.png", artist: "Devin Night" },
  { key: "goblins-kobolds-worg-22", label: "Worg", category: "Goblins & Kobolde", file: "goblins-kobolds/worg_22.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-berserker", label: "Ogre Berserker", category: "Orks & Trolle", file: "orcs-trolls/Ogre_berserker.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-dead-28", label: "Ogre Dead", category: "Orks & Trolle", file: "orcs-trolls/Ogre_dead_28.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-dead-29", label: "Ogre Dead", category: "Orks & Trolle", file: "orcs-trolls/Ogre_dead_29.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter", label: "Ogre Fighter", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter2", label: "Ogre Fighter2", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter2.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter3", label: "Ogre Fighter3", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter3.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter4", label: "Ogre Fighter4", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter4.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter5", label: "Ogre Fighter5", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter5.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-fighter6", label: "Ogre Fighter6", category: "Orks & Trolle", file: "orcs-trolls/Ogre_fighter6.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-shaman", label: "Ogre Shaman", category: "Orks & Trolle", file: "orcs-trolls/Ogre_shaman.png", artist: "Devin Night" },
  { key: "orcs-trolls-ogre-shaman2", label: "Ogre Shaman2", category: "Orks & Trolle", file: "orcs-trolls/Ogre_shaman2.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-archer", label: "Orc Archer", category: "Orks & Trolle", file: "orcs-trolls/Orc_archer.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-chieftan", label: "Orc Chieftan", category: "Orks & Trolle", file: "orcs-trolls/Orc_chieftan.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-chieftan2", label: "Orc Chieftan2", category: "Orks & Trolle", file: "orcs-trolls/Orc_chieftan2.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-crossbowman", label: "Orc Crossbowman", category: "Orks & Trolle", file: "orcs-trolls/Orc_crossbowman.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter", label: "Orc Fighter", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter2", label: "Orc Fighter2", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter2.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter3", label: "Orc Fighter3", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter3.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter4", label: "Orc Fighter4", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter4.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter5", label: "Orc Fighter5", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter5.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter6", label: "Orc Fighter6", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter6.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-fighter7", label: "Orc Fighter7", category: "Orks & Trolle", file: "orcs-trolls/Orc_fighter7.png", artist: "Devin Night" },
  { key: "orcs-trolls-orc-shaman", label: "Orc Shaman", category: "Orks & Trolle", file: "orcs-trolls/Orc_shaman.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-dead-27", label: "Troll Dead", category: "Orks & Trolle", file: "orcs-trolls/Troll_dead_27.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter", label: "Troll Fighter", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter1", label: "Troll Fighter1", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter1.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter2", label: "Troll Fighter2", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter2.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter3", label: "Troll Fighter3", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter3.png", artist: "Devin Night" },
  { key: "orcs-trolls-troll-fighter4", label: "Troll Fighter4", category: "Orks & Trolle", file: "orcs-trolls/Troll_fighter4.png", artist: "Devin Night" },
  { key: "pirates-dog-hound", label: "Dog Hound", category: "Piraten", file: "pirates/dog_hound.png", artist: "Devin Night" },
  { key: "pirates-female-blacksmith-hammer", label: "Female Blacksmith Hammer", category: "Piraten", file: "pirates/female_blacksmith_hammer.png", artist: "Devin Night" },
  { key: "pirates-female-captian-sword", label: "Female Captian Sword", category: "Piraten", file: "pirates/female_captian_sword.png", artist: "Devin Night" },
  { key: "pirates-female-cleaver", label: "Female Cleaver", category: "Piraten", file: "pirates/female_cleaver.png", artist: "Devin Night" },
  { key: "pirates-female-lady-dress", label: "Female Lady Dress", category: "Piraten", file: "pirates/female_lady_dress.png", artist: "Devin Night" },
  { key: "pirates-female-long-knife", label: "Female Long Knife", category: "Piraten", file: "pirates/female_long_knife.png", artist: "Devin Night" },
  { key: "pirates-female-mage-spell", label: "Female Mage Spell", category: "Piraten", file: "pirates/female_mage_spell.png", artist: "Devin Night" },
  { key: "pirates-female-shortsword", label: "Female Shortsword", category: "Piraten", file: "pirates/female_shortsword.png", artist: "Devin Night" },
  { key: "pirates-female-sword-tattoo", label: "Female Sword Tattoo", category: "Piraten", file: "pirates/female_sword_tattoo.png", artist: "Devin Night" },
  { key: "pirates-female-wild-mage", label: "Female Wild Mage", category: "Piraten", file: "pirates/female_wild_mage.png", artist: "Devin Night" },
  { key: "pirates-female-young-running", label: "Female Young Running", category: "Piraten", file: "pirates/female_young_running.png", artist: "Devin Night" },
  { key: "pirates-male-axe-fighter", label: "Male Axe Fighter", category: "Piraten", file: "pirates/male_axe_fighter.png", artist: "Devin Night" },
  { key: "pirates-male-blunderbus-canon", label: "Male Blunderbus Canon", category: "Piraten", file: "pirates/male_blunderbus_canon.png", artist: "Devin Night" },
  { key: "pirates-male-captain-sword", label: "Male Captain Sword", category: "Piraten", file: "pirates/male_captain_sword.png", artist: "Devin Night" },
  { key: "pirates-male-captain-trident", label: "Male Captain Trident", category: "Piraten", file: "pirates/male_captain_trident.png", artist: "Devin Night" },
  { key: "pirates-male-crossbow", label: "Male Crossbow", category: "Piraten", file: "pirates/male_crossbow.png", artist: "Devin Night" },
  { key: "pirates-male-crossbow-large", label: "Male Crossbow Large", category: "Piraten", file: "pirates/male_crossbow_large.png", artist: "Devin Night" },
  { key: "pirates-male-grappling-hook-boarder", label: "Male Grappling Hook Boarder", category: "Piraten", file: "pirates/male_grappling_hook_boarder.png", artist: "Devin Night" },
  { key: "pirates-male-katana-eyepatch", label: "Male Katana Eyepatch", category: "Piraten", file: "pirates/male_katana_eyepatch.png", artist: "Devin Night" },
  { key: "pirates-male-knife-urchin", label: "Male Knife Urchin", category: "Piraten", file: "pirates/male_knife_urchin.png", artist: "Devin Night" },
  { key: "pirates-male-mage", label: "Male Mage", category: "Piraten", file: "pirates/male_mage.png", artist: "Devin Night" },
  { key: "pirates-male-noble-diplomat", label: "Male Noble Diplomat", category: "Piraten", file: "pirates/male_noble_diplomat.png", artist: "Devin Night" },
  { key: "pirates-male-pirate-crossbow", label: "Male Pirate Crossbow", category: "Piraten", file: "pirates/male_pirate_crossbow.png", artist: "Devin Night" },
  { key: "pirates-male-pirate-swrod-shield", label: "Male Pirate Swrod Shield", category: "Piraten", file: "pirates/male_pirate_swrod_shield.png", artist: "Devin Night" },
  { key: "pirates-male-purple-rapier", label: "Male Purple Rapier", category: "Piraten", file: "pirates/male_purple_rapier.png", artist: "Devin Night" },
  { key: "pirates-male-rapier-figher", label: "Male Rapier Figher", category: "Piraten", file: "pirates/male_rapier_figher.png", artist: "Devin Night" },
  { key: "pirates-male-red-sword", label: "Male Red Sword", category: "Piraten", file: "pirates/male_red_sword.png", artist: "Devin Night" },
  { key: "pirates-male-rower-left", label: "Male Rower Left", category: "Piraten", file: "pirates/male_rower_left.png", artist: "Devin Night" },
  { key: "pirates-male-rower-middle", label: "Male Rower Middle", category: "Piraten", file: "pirates/male_rower_middle.png", artist: "Devin Night" },
  { key: "pirates-male-rower-oars", label: "Male Rower Oars", category: "Piraten", file: "pirates/male_rower_oars.png", artist: "Devin Night" },
  { key: "pirates-male-rower-right", label: "Male Rower Right", category: "Piraten", file: "pirates/male_rower_right.png", artist: "Devin Night" },
  { key: "pirates-male-rowers-left", label: "Male Rowers Left", category: "Piraten", file: "pirates/male_rowers_left.png", artist: "Devin Night" },
  { key: "pirates-male-rowers-right", label: "Male Rowers Right", category: "Piraten", file: "pirates/male_rowers_right.png", artist: "Devin Night" },
  { key: "pirates-male-sunburnt-brawler", label: "Male Sunburnt Brawler", category: "Piraten", file: "pirates/male_sunburnt_brawler.png", artist: "Devin Night" },
  { key: "pirates-male-sword", label: "Male Sword", category: "Piraten", file: "pirates/male_sword.png", artist: "Devin Night" },
  { key: "pirates-male-sword-dagger", label: "Male Sword Dagger", category: "Piraten", file: "pirates/male_sword_dagger.png", artist: "Devin Night" },
  { key: "pirates-male-sword-hook", label: "Male Sword Hook", category: "Piraten", file: "pirates/male_sword_hook.png", artist: "Devin Night" },
  { key: "pirates-male-sword-stalker", label: "Male Sword Stalker", category: "Piraten", file: "pirates/male_sword_stalker.png", artist: "Devin Night" },
  { key: "pirates-male-swordsman-scimitar", label: "Male Swordsman Scimitar", category: "Piraten", file: "pirates/male_swordsman_scimitar.png", artist: "Devin Night" },
  { key: "pirates-male-viking-axe", label: "Male Viking Axe", category: "Piraten", file: "pirates/male_viking_axe.png", artist: "Devin Night" },
  { key: "pirates-male-viking-axe-shiled", label: "Male Viking Axe Shiled", category: "Piraten", file: "pirates/male_viking_axe_shiled.png", artist: "Devin Night" },
  { key: "dm-essentials-bullman-poleaxe", label: "Bullman Poleaxe", category: "SL-Extras", file: "dm-essentials/bullman_poleaxe.png", artist: "Devin Night" },
  { key: "dm-essentials-chimera", label: "Chimera", category: "SL-Extras", file: "dm-essentials/chimera.png", artist: "Devin Night" },
  { key: "dm-essentials-gryphon", label: "Gryphon", category: "SL-Extras", file: "dm-essentials/gryphon.png", artist: "Devin Night" },
  { key: "dm-essentials-harpy-1", label: "Harpy", category: "SL-Extras", file: "dm-essentials/harpy_1.png", artist: "Devin Night" },
  { key: "dm-essentials-harpy-brown-flying", label: "Harpy Brown Flying", category: "SL-Extras", file: "dm-essentials/harpy_brown_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-harpy-purple", label: "Harpy Purple", category: "SL-Extras", file: "dm-essentials/harpy_purple.png", artist: "Devin Night" },
  { key: "dm-essentials-harpy-purple-flying", label: "Harpy Purple Flying", category: "SL-Extras", file: "dm-essentials/harpy_purple_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-hippogriff", label: "Hippogriff", category: "SL-Extras", file: "dm-essentials/hippogriff.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra-1head", label: "Hydra 1head", category: "SL-Extras", file: "dm-essentials/hydra_1head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra-2head", label: "Hydra 2head", category: "SL-Extras", file: "dm-essentials/hydra_2head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra-5head", label: "Hydra 5head", category: "SL-Extras", file: "dm-essentials/hydra_5head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra-8head", label: "Hydra 8head", category: "SL-Extras", file: "dm-essentials/hydra_8head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra2-1head", label: "Hydra2 1head", category: "SL-Extras", file: "dm-essentials/hydra2_1head.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra2-2headed", label: "Hydra2 2headed", category: "SL-Extras", file: "dm-essentials/hydra2_2headed.png", artist: "Devin Night" },
  { key: "dm-essentials-hydra2-8head", label: "Hydra2 8head", category: "SL-Extras", file: "dm-essentials/hydra2_8head.png", artist: "Devin Night" },
  { key: "dm-essentials-jhydra2-5head", label: "Jhydra2 5head", category: "SL-Extras", file: "dm-essentials/jhydra2_5head.png", artist: "Devin Night" },
  { key: "dm-essentials-lion", label: "Lion", category: "SL-Extras", file: "dm-essentials/lion.png", artist: "Devin Night" },
  { key: "dm-essentials-lion-winged", label: "Lion Winged", category: "SL-Extras", file: "dm-essentials/lion_winged.png", artist: "Devin Night" },
  { key: "dm-essentials-manticore-flying", label: "Manticore Flying", category: "SL-Extras", file: "dm-essentials/manticore_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-manticore-ground", label: "Manticore Ground", category: "SL-Extras", file: "dm-essentials/manticore_ground.png", artist: "Devin Night" },
  { key: "dm-essentials-medusa-red", label: "Medusa Red", category: "SL-Extras", file: "dm-essentials/medusa_red.png", artist: "Devin Night" },
  { key: "dm-essentials-medusa-tan", label: "Medusa Tan", category: "SL-Extras", file: "dm-essentials/medusa_tan.png", artist: "Devin Night" },
  { key: "dm-essentials-minotaur-axe", label: "Minotaur Axe", category: "SL-Extras", file: "dm-essentials/minotaur_axe.png", artist: "Devin Night" },
  { key: "dm-essentials-minotaur-axe-2", label: "Minotaur Axe", category: "SL-Extras", file: "dm-essentials/minotaur_axe_2.png", artist: "Devin Night" },
  { key: "dm-essentials-minotaur-axe-3", label: "Minotaur Axe", category: "SL-Extras", file: "dm-essentials/minotaur_axe_3.png", artist: "Devin Night" },
  { key: "dm-essentials-satyr-axe", label: "Satyr Axe", category: "SL-Extras", file: "dm-essentials/satyr_axe.png", artist: "Devin Night" },
  { key: "dm-essentials-satyr-staff", label: "Satyr Staff", category: "SL-Extras", file: "dm-essentials/satyr_staff.png", artist: "Devin Night" },
  { key: "dm-essentials-satyr-staff-2", label: "Satyr Staff", category: "SL-Extras", file: "dm-essentials/satyr_staff_2.png", artist: "Devin Night" },
  { key: "dm-essentials-satyr-whip", label: "Satyr Whip", category: "SL-Extras", file: "dm-essentials/satyr_whip.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-2headed", label: "Wyvern 2headed", category: "SL-Extras", file: "dm-essentials/wyvern_2headed.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-blue", label: "Wyvern Blue", category: "SL-Extras", file: "dm-essentials/wyvern_blue.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-blue-flying", label: "Wyvern Blue Flying", category: "SL-Extras", file: "dm-essentials/wyvern_blue_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-blue-ground", label: "Wyvern Blue Ground", category: "SL-Extras", file: "dm-essentials/wyvern_blue_ground.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-green", label: "Wyvern Green", category: "SL-Extras", file: "dm-essentials/wyvern_green.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-green-flying", label: "Wyvern Green Flying", category: "SL-Extras", file: "dm-essentials/wyvern_green_flying.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-green-sitting", label: "Wyvern Green Sitting", category: "SL-Extras", file: "dm-essentials/wyvern_green_sitting.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-purple", label: "Wyvern Purple", category: "SL-Extras", file: "dm-essentials/wyvern_purple.png", artist: "Devin Night" },
  { key: "dm-essentials-wyvern-tan-flying", label: "Wyvern Tan Flying", category: "SL-Extras", file: "dm-essentials/wyvern_tan_flying.png", artist: "Devin Night" },
  { key: "townsfolk-bartender-male", label: "Bartender Male", category: "Stadtvolk", file: "townsfolk/bartender_male.png", artist: "Devin Night" },
  { key: "townsfolk-blacksmith-male", label: "Blacksmith Male", category: "Stadtvolk", file: "townsfolk/blacksmith_male.png", artist: "Devin Night" },
  { key: "townsfolk-boy-running", label: "Boy Running", category: "Stadtvolk", file: "townsfolk/boy_running.png", artist: "Devin Night" },
  { key: "townsfolk-boy-stick", label: "Boy Stick", category: "Stadtvolk", file: "townsfolk/boy_stick.png", artist: "Devin Night" },
  { key: "townsfolk-builder-male", label: "Builder Male", category: "Stadtvolk", file: "townsfolk/builder_male.png", artist: "Devin Night" },
  { key: "townsfolk-buthcer-male", label: "Buthcer Male", category: "Stadtvolk", file: "townsfolk/buthcer_male.png", artist: "Devin Night" },
  { key: "townsfolk-cows", label: "Cows", category: "Stadtvolk", file: "townsfolk/cows.png", artist: "Devin Night" },
  { key: "townsfolk-farmer-rake", label: "Farmer Rake", category: "Stadtvolk", file: "townsfolk/farmer_rake.png", artist: "Devin Night" },
  { key: "townsfolk-florist-lady", label: "Florist Lady", category: "Stadtvolk", file: "townsfolk/florist_lady.png", artist: "Devin Night" },
  { key: "townsfolk-gardener-male", label: "Gardener Male", category: "Stadtvolk", file: "townsfolk/gardener_male.png", artist: "Devin Night" },
  { key: "townsfolk-gilr-red", label: "Gilr Red", category: "Stadtvolk", file: "townsfolk/gilr_red.png", artist: "Devin Night" },
  { key: "townsfolk-girl-blue", label: "Girl Blue", category: "Stadtvolk", file: "townsfolk/girl_blue.png", artist: "Devin Night" },
  { key: "townsfolk-half-orc-bartender", label: "Half Orc Bartender", category: "Stadtvolk", file: "townsfolk/half_orc_bartender.png", artist: "Devin Night" },
  { key: "townsfolk-hunter-trapper", label: "Hunter Trapper", category: "Stadtvolk", file: "townsfolk/hunter_trapper.png", artist: "Devin Night" },
  { key: "townsfolk-local-female", label: "Local Female", category: "Stadtvolk", file: "townsfolk/local_female.png", artist: "Devin Night" },
  { key: "townsfolk-local-female-2", label: "Local Female", category: "Stadtvolk", file: "townsfolk/local_female_2.png", artist: "Devin Night" },
  { key: "townsfolk-local-male", label: "Local Male", category: "Stadtvolk", file: "townsfolk/local_male.png", artist: "Devin Night" },
  { key: "townsfolk-local-male-2", label: "Local Male", category: "Stadtvolk", file: "townsfolk/local_male_2.png", artist: "Devin Night" },
  { key: "townsfolk-merchant-female-wizard", label: "Merchant Female Wizard", category: "Stadtvolk", file: "townsfolk/merchant_female_wizard.png", artist: "Devin Night" },
  { key: "townsfolk-minor-noble-female", label: "Minor Noble Female", category: "Stadtvolk", file: "townsfolk/minor_noble_female.png", artist: "Devin Night" },
  { key: "townsfolk-minor-noble-male", label: "Minor Noble Male", category: "Stadtvolk", file: "townsfolk/minor_noble_male.png", artist: "Devin Night" },
  { key: "townsfolk-packbearer-porter", label: "Packbearer Porter", category: "Stadtvolk", file: "townsfolk/packbearer_porter.png", artist: "Devin Night" },
  { key: "townsfolk-peasant-farmer-hay", label: "Peasant Farmer Hay", category: "Stadtvolk", file: "townsfolk/Peasant_farmer_hay.png", artist: "Devin Night" },
  { key: "townsfolk-peasant-water-fetcher", label: "Peasant Water Fetcher", category: "Stadtvolk", file: "townsfolk/Peasant_water_fetcher.png", artist: "Devin Night" },
  { key: "townsfolk-porter-male", label: "Porter Male", category: "Stadtvolk", file: "townsfolk/porter_male.png", artist: "Devin Night" },
  { key: "townsfolk-scholar-female", label: "Scholar Female", category: "Stadtvolk", file: "townsfolk/scholar_female.png", artist: "Devin Night" },
  { key: "townsfolk-scholar-female-2", label: "Scholar Female", category: "Stadtvolk", file: "townsfolk/scholar_female_2.png", artist: "Devin Night" },
  { key: "townsfolk-server-male", label: "Server Male", category: "Stadtvolk", file: "townsfolk/server_male.png", artist: "Devin Night" },
  { key: "undead-female-ghost-blue-2", label: "Female Ghost Blue", category: "Untote", file: "undead/female_ghost_blue_2.png", artist: "Devin Night" },
  { key: "undead-ghost-female-blue", label: "Ghost Female Blue", category: "Untote", file: "undead/ghost_female_blue.png", artist: "Devin Night" },
  { key: "undead-ghost-white-evil", label: "Ghost White Evil", category: "Untote", file: "undead/ghost_white_evil.png", artist: "Devin Night" },
  { key: "undead-ghost-wolf-silver", label: "Ghost Wolf Silver", category: "Untote", file: "undead/ghost_wolf_silver.png", artist: "Devin Night" },
  { key: "undead-lich-blue", label: "Lich Blue", category: "Untote", file: "undead/lich_blue.png", artist: "Devin Night" },
  { key: "undead-lich-masked-mage", label: "Lich Masked Mage", category: "Untote", file: "undead/lich_masked_mage.png", artist: "Devin Night" },
  { key: "undead-lich-skull-evil", label: "Lich Skull Evil", category: "Untote", file: "undead/lich_skull_evil.png", artist: "Devin Night" },
  { key: "undead-skeleton-archer-red", label: "Skeleton Archer Red", category: "Untote", file: "undead/skeleton_archer_red.png", artist: "Devin Night" },
  { key: "undead-skeleton-archer-walking", label: "Skeleton Archer Walking", category: "Untote", file: "undead/skeleton_archer_walking.png", artist: "Devin Night" },
  { key: "undead-skeleton-axe", label: "Skeleton Axe", category: "Untote", file: "undead/skeleton_axe.png", artist: "Devin Night" },
  { key: "undead-skeleton-axe-shield", label: "Skeleton Axe Shield", category: "Untote", file: "undead/skeleton_axe_shield.png", artist: "Devin Night" },
  { key: "undead-skeleton-crawling-legless", label: "Skeleton Crawling Legless", category: "Untote", file: "undead/skeleton_crawling_legless.png", artist: "Devin Night" },
  { key: "undead-skeleton-crossbow", label: "Skeleton Crossbow", category: "Untote", file: "undead/skeleton_crossbow.png", artist: "Devin Night" },
  { key: "undead-skeleton-crossbow-armored", label: "Skeleton Crossbow Armored", category: "Untote", file: "undead/skeleton_crossbow_armored.png", artist: "Devin Night" },
  { key: "undead-skeleton-dagger", label: "Skeleton Dagger", category: "Untote", file: "undead/skeleton_dagger.png", artist: "Devin Night" },
  { key: "undead-skeleton-mace", label: "Skeleton Mace", category: "Untote", file: "undead/skeleton_mace.png", artist: "Devin Night" },
  { key: "undead-skeleton-sword-shield", label: "Skeleton Sword Shield", category: "Untote", file: "undead/skeleton_sword_shield.png", artist: "Devin Night" },
  { key: "undead-wight-bone", label: "Wight Bone", category: "Untote", file: "undead/wight_bone.png", artist: "Devin Night" },
  { key: "undead-wight-bone-club", label: "Wight Bone Club", category: "Untote", file: "undead/wight_bone_club.png", artist: "Devin Night" },
  { key: "undead-wight-rusty-sword", label: "Wight Rusty Sword", category: "Untote", file: "undead/wight_rusty_sword.png", artist: "Devin Night" },
  { key: "undead-wight-shovel", label: "Wight Shovel", category: "Untote", file: "undead/wight_shovel.png", artist: "Devin Night" },
  { key: "undead-zombie-female-green", label: "Zombie Female Green", category: "Untote", file: "undead/zombie_female_green.png", artist: "Devin Night" },
  { key: "undead-zombie-female-red", label: "Zombie Female Red", category: "Untote", file: "undead/zombie_female_red.png", artist: "Devin Night" },
  { key: "undead-zombie-male-crawling", label: "Zombie Male Crawling", category: "Untote", file: "undead/zombie_male_crawling.png", artist: "Devin Night" },
  { key: "undead-zombie-male-footdragging", label: "Zombie Male Footdragging", category: "Untote", file: "undead/zombie_male_footdragging.png", artist: "Devin Night" },
  { key: "undead-zombie-male-grren", label: "Zombie Male Grren", category: "Untote", file: "undead/zombie_male_grren.png", artist: "Devin Night" },
  { key: "undead-zombie-male-yellow", label: "Zombie Male Yellow", category: "Untote", file: "undead/zombie_male_yellow.png", artist: "Devin Night" },
  { key: "undead-zombie-wolf", label: "Zombie Wolf", category: "Untote", file: "undead/zombie_wolf.png", artist: "Devin Night" },
  { key: "freebies-beetle-giant-01", label: "Beetle Giant", category: "Verschiedenes", file: "freebies/Beetle_Giant_01.png", artist: "Devin Night" },
  { key: "freebies-bugbear-chieftan-10", label: "Bugbear Chieftan", category: "Verschiedenes", file: "freebies/Bugbear_Chieftan_10.png", artist: "Devin Night" },
  { key: "freebies-bugbear-mace-04", label: "Bugbear Mace", category: "Verschiedenes", file: "freebies/Bugbear_Mace_04.png", artist: "Devin Night" },
  { key: "freebies-caveman-01", label: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_01.png", artist: "Devin Night" },
  { key: "freebies-caveman-02", label: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_02.png", artist: "Devin Night" },
  { key: "freebies-caveman-03", label: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_03.png", artist: "Devin Night" },
  { key: "freebies-caveman-08", label: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_08.png", artist: "Devin Night" },
  { key: "freebies-caveman-10", label: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_10.png", artist: "Devin Night" },
  { key: "freebies-caveman-11", label: "Caveman", category: "Verschiedenes", file: "freebies/Caveman_11.png", artist: "Devin Night" },
  { key: "freebies-chaos-spawn-14", label: "Chaos Spawn", category: "Verschiedenes", file: "freebies/Chaos_Spawn_14.png", artist: "Devin Night" },
  { key: "freebies-chaos-spawn-17", label: "Chaos Spawn", category: "Verschiedenes", file: "freebies/Chaos_Spawn_17.png", artist: "Devin Night" },
  { key: "freebies-clockwork-slasher-13", label: "Clockwork Slasher", category: "Verschiedenes", file: "freebies/Clockwork_Slasher_13.png", artist: "Devin Night" },
  { key: "freebies-demon-pit-15", label: "Demon Pit", category: "Verschiedenes", file: "freebies/Demon_Pit_15.png", artist: "Devin Night" },
  { key: "freebies-demon-slime-09", label: "Demon Slime", category: "Verschiedenes", file: "freebies/Demon_Slime_09.png", artist: "Devin Night" },
  { key: "freebies-dragon-green-14", label: "Dragon Green", category: "Verschiedenes", file: "freebies/Dragon_Green_14.png", artist: "Devin Night" },
  { key: "freebies-dragon-red-08", label: "Dragon Red", category: "Verschiedenes", file: "freebies/Dragon_Red_08.png", artist: "Devin Night" },
  { key: "freebies-dragonman-23", label: "Dragonman", category: "Verschiedenes", file: "freebies/DragonMan_23.png", artist: "Devin Night" },
  { key: "freebies-evileye-06", label: "Evileye", category: "Verschiedenes", file: "freebies/EvilEye_06.png", artist: "Devin Night" },
  { key: "freebies-evileye-16", label: "Evileye", category: "Verschiedenes", file: "freebies/EvilEye_16.png", artist: "Devin Night" },
  { key: "freebies-frogmonster-07", label: "Frogmonster", category: "Verschiedenes", file: "freebies/Frogmonster_07.png", artist: "Devin Night" },
  { key: "freebies-giant-hill-16", label: "Giant Hill", category: "Verschiedenes", file: "freebies/Giant_Hill_16.png", artist: "Devin Night" },
  { key: "freebies-giantworm-18", label: "Giantworm", category: "Verschiedenes", file: "freebies/GiantWorm_18.png", artist: "Devin Night" },
  { key: "freebies-grey-stalker-06", label: "Grey Stalker", category: "Verschiedenes", file: "freebies/Grey_Stalker_06.png", artist: "Devin Night" },
  { key: "freebies-grey-swordsman-13", label: "Grey Swordsman", category: "Verschiedenes", file: "freebies/Grey_Swordsman_13.png", artist: "Devin Night" },
  { key: "freebies-lavaman-12", label: "Lavaman", category: "Verschiedenes", file: "freebies/Lavaman_12.png", artist: "Devin Night" },
  { key: "freebies-messenger-mounted-07", label: "Messenger Mounted", category: "Verschiedenes", file: "freebies/Messenger_Mounted_07.png", artist: "Devin Night" },
  { key: "freebies-polarbear-02", label: "Polarbear", category: "Verschiedenes", file: "freebies/Polarbear_02.png", artist: "Devin Night" },
  { key: "freebies-rat-giant-05", label: "Rat Giant", category: "Verschiedenes", file: "freebies/Rat_Giant_05.png", artist: "Devin Night" },
  { key: "freebies-wizard-evil-11", label: "Wizard Evil", category: "Verschiedenes", file: "freebies/Wizard_Evil_11.png", artist: "Devin Night" },
  { key: "freebies-zombie-rotting-05", label: "Zombie Rotting", category: "Verschiedenes", file: "freebies/Zombie_Rotting_05.png", artist: "Devin Night" },
  { key: "freebies-zombie-rotting-12", label: "Zombie Rotting", category: "Verschiedenes", file: "freebies/Zombie_Rotting_12.png", artist: "Devin Night" },
  { key: "guards-nobles-human-alchemist-flasks-green", label: "Human Alchemist Flasks Green", category: "Wachen & Adlige", file: "guards-nobles/Human_Alchemist_Flasks_Green.png", artist: "Devin Night" },
  { key: "guards-nobles-human-alchemist-flasks-redfantasynoblenpctokenfree", label: "Human Alchemist Flasks Red[fantasy,noble,npc,token,free]", category: "Wachen & Adlige", file: "guards-nobles/Human_Alchemist_Flasks_Red[fantasy,noble,NPC,token,free].png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe", label: "Human Guard Axe", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-helmet", label: "Human Guard Axe Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-helmet-2", label: "Human Guard Axe Helmet-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Helmet-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-helmet-3", label: "Human Guard Axe Helmet-3", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Helmet-3.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-purple", label: "Human Guard Axe Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-purple-2", label: "Human Guard Axe Purple-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Purple-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-purple-3", label: "Human Guard Axe Purple-3", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe_Purple-3.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-2", label: "Human Guard Axe-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-axe-3", label: "Human Guard Axe-3", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Axe-3.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-bow-helmet", label: "Human Guard Bow Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Bow_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-bow-purple", label: "Human Guard Bow Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Bow_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-helmet", label: "Human Guard Crossbow Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-helmet-2", label: "Human Guard Crossbow Helmet-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow_Helmet-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-purple", label: "Human Guard Crossbow Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-purple-2", label: "Human Guard Crossbow Purple-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow_Purple-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-crossbow-2", label: "Human Guard Crossbow-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Crossbow-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-shield-helmet", label: "Human Guard Shield Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Shield_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-spear-purple", label: "Human Guard Spear Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Spear_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-spear-shield", label: "Human Guard Spear-shield", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Spear-Shield.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-spear-shield-helmet", label: "Human Guard Spear-shield Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Spear-Shield_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-spear-shield-purple", label: "Human Guard Spear-shield Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Spear-Shield_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-helmet", label: "Human Guard Sword Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-purple", label: "Human Guard Sword Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-helmet", label: "Human Guard Sword-shield Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-helmet-2", label: "Human Guard Sword-shield Helmet-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield_Helmet-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-purple", label: "Human Guard Sword-shield Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-purple-2", label: "Human Guard Sword-shield Purple-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield_Purple-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-sword-shield-2", label: "Human Guard Sword-shield-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard_Sword-Shield-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-commander-helmet", label: "Human Guard-commander Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard-Commander_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-commander-purple", label: "Human Guard-commander Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard-Commander_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-commander-spear-purple", label: "Human Guard-commander Spear Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard-commander_Spear_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-guard-commander-sword-helmet", label: "Human Guard-commander Sword Helmet", category: "Wachen & Adlige", file: "guards-nobles/Human_Guard-Commander_Sword_Helmet.png", artist: "Devin Night" },
  { key: "guards-nobles-human-jester", label: "Human Jester", category: "Wachen & Adlige", file: "guards-nobles/Human_Jester.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lady-blue", label: "Human Lady Blue", category: "Wachen & Adlige", file: "guards-nobles/Human_Lady_Blue.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lady-purple", label: "Human Lady Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Lady_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lady-sitting-pink", label: "Human Lady Sitting Pink", category: "Wachen & Adlige", file: "guards-nobles/Human_Lady_Sitting_Pink.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lady-sitting-purple", label: "Human Lady Sitting Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Lady_Sitting_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lord-purple", label: "Human Lord Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Lord_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lord-red", label: "Human Lord Red", category: "Wachen & Adlige", file: "guards-nobles/Human_Lord_Red.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lord-rod-purple", label: "Human Lord Rod Purple", category: "Wachen & Adlige", file: "guards-nobles/Human_Lord_Rod_Purple.png", artist: "Devin Night" },
  { key: "guards-nobles-human-lord-rogue-sword", label: "Human Lord-rogue Sword", category: "Wachen & Adlige", file: "guards-nobles/Human_Lord-Rogue_Sword.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-bow-2fantasynoblenpctokenfree", label: "Human Nomad Bow-2[fantasy,noble,npc,token,free]", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Bow-2[fantasy,noble,NPC,token,free].png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-bowfantasynoblenpctokenfree", label: "Human Nomad Bow[fantasy,noble,npc,token,free]", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Bow[fantasy,noble,NPC,token,free].png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-scimitar-shield", label: "Human Nomad Scimitar-shield", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Scimitar-Shield.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-scimitar-shield-2", label: "Human Nomad Scimitar-shield-2", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Scimitar-Shield-2.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-scimitarfantasynoblenpctokenfree", label: "Human Nomad Scimitar[fantasy,noble,npc,token,free]", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Scimitar[fantasy,noble,NPC,token,free].png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-scimitars", label: "Human Nomad Scimitars", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Scimitars.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-spear", label: "Human Nomad Spear", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Spear.png", artist: "Devin Night" },
  { key: "guards-nobles-human-nomad-spear-shield", label: "Human Nomad Spear-shield", category: "Wachen & Adlige", file: "guards-nobles/Human_Nomad_Spear-Shield.png", artist: "Devin Night" },
  { key: "guards-nobles-human-witch-black", label: "Human Witch Black", category: "Wachen & Adlige", file: "guards-nobles/Human_Witch_Black.png", artist: "Devin Night" },
  { key: "guards-nobles-human-witch-blue", label: "Human Witch Blue", category: "Wachen & Adlige", file: "guards-nobles/Human_Witch_Blue.png", artist: "Devin Night" },
  { key: "guards-nobles-human-witch-green", label: "Human Witch Green", category: "Wachen & Adlige", file: "guards-nobles/Human_Witch_Green.png", artist: "Devin Night" },
  { key: "guards-nobles-human-witch-staff-red", label: "Human Witch Staff Red", category: "Wachen & Adlige", file: "guards-nobles/Human_Witch_Staff_Red.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-axe-shield", label: "Dwarf Female Axe Shield", category: "Zwerge", file: "dwarves/dwarf_female_axe_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-axe-shield-2", label: "Dwarf Female Axe Shield", category: "Zwerge", file: "dwarves/dwarf_female_axe_shield_2.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-fighter-axe", label: "Dwarf Female Fighter Axe", category: "Zwerge", file: "dwarves/dwarf_female_fighter_axe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-hammer-shield", label: "Dwarf Female Hammer Shield", category: "Zwerge", file: "dwarves/dwarf_female_hammer_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-pick-plate", label: "Dwarf Female Pick Plate", category: "Zwerge", file: "dwarves/dwarf_female_pick_plate.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-female-spear", label: "Dwarf Female Spear", category: "Zwerge", file: "dwarves/dwarf_female_spear.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-axe-shield-2", label: "Dwarf Male Axe Shield", category: "Zwerge", file: "dwarves/dwarf_male_axe_shield_2.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-axe-shield-gold", label: "Dwarf Male Axe Shield Gold", category: "Zwerge", file: "dwarves/dwarf_male_axe_shield_gold.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-axe-shield-green", label: "Dwarf Male Axe Shield Green", category: "Zwerge", file: "dwarves/dwarf_male_axe_shield_green.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-axe-shield-silver", label: "Dwarf Male Axe Shield Silver", category: "Zwerge", file: "dwarves/dwarf_male_axe_shield_silver.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-blunderbus-canon", label: "Dwarf Male Blunderbus Canon", category: "Zwerge", file: "dwarves/dwarf_male_blunderbus_canon.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-brawler", label: "Dwarf Male Brawler", category: "Zwerge", file: "dwarves/dwarf_male_brawler.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-cleric-yellow", label: "Dwarf Male Cleric Yellow", category: "Zwerge", file: "dwarves/dwarf_male_cleric_yellow.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-copper-hammer", label: "Dwarf Male Copper Hammer", category: "Zwerge", file: "dwarves/dwarf_male_copper_hammer.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-crossbow-2", label: "Dwarf Male Crossbow", category: "Zwerge", file: "dwarves/dwarf_male_crossbow_2.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-crossbow-red", label: "Dwarf Male Crossbow Red", category: "Zwerge", file: "dwarves/dwarf_male_crossbow_red.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-crosswbow-green-3", label: "Dwarf Male Crosswbow Green", category: "Zwerge", file: "dwarves/dwarf_male_crosswbow_green_3.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-doubleaxe", label: "Dwarf Male Doubleaxe", category: "Zwerge", file: "dwarves/dwarf_male_doubleaxe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-doubleaxe-shield", label: "Dwarf Male Doubleaxe Shield", category: "Zwerge", file: "dwarves/dwarf_male_doubleaxe_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-doubleaxe-shield-mail", label: "Dwarf Male Doubleaxe Shield Mail", category: "Zwerge", file: "dwarves/dwarf_male_doubleaxe_shield_mail.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-fighter-mace", label: "Dwarf Male Fighter Mace", category: "Zwerge", file: "dwarves/dwarf_male_fighter_mace.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-fighter-mage", label: "Dwarf Male Fighter Mage", category: "Zwerge", file: "dwarves/dwarf_male_fighter_mage.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-fighter-scythe", label: "Dwarf Male Fighter Scythe", category: "Zwerge", file: "dwarves/dwarf_male_fighter_scythe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-flag-standard", label: "Dwarf Male Flag Standard", category: "Zwerge", file: "dwarves/dwarf_male_flag_standard.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-hammer-shield", label: "Dwarf Male Hammer Shield", category: "Zwerge", file: "dwarves/dwarf_male_hammer_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-hammer-shield-green", label: "Dwarf Male Hammer Shield Green", category: "Zwerge", file: "dwarves/dwarf_male_hammer_shield_green.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-handaxes-red", label: "Dwarf Male Handaxes Red", category: "Zwerge", file: "dwarves/dwarf_male_handaxes_red.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-mace-hammer-red", label: "Dwarf Male Mace Hammer Red", category: "Zwerge", file: "dwarves/dwarf_male_mace_hammer_red.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-monk", label: "Dwarf Male Monk", category: "Zwerge", file: "dwarves/dwarf_male_monk.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-pale-axe", label: "Dwarf Male Pale Axe", category: "Zwerge", file: "dwarves/dwarf_male_pale_axe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-pick-shield", label: "Dwarf Male Pick Shield", category: "Zwerge", file: "dwarves/dwarf_male_pick_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-plate-flail-shield", label: "Dwarf Male Plate Flail Shield", category: "Zwerge", file: "dwarves/dwarf_male_plate_flail_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-plate-hammer-shield", label: "Dwarf Male Plate Hammer Shield", category: "Zwerge", file: "dwarves/dwarf_male_plate_hammer_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-poleaxe", label: "Dwarf Male Poleaxe", category: "Zwerge", file: "dwarves/dwarf_male_poleaxe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-priest-longhammer", label: "Dwarf Male Priest Longhammer", category: "Zwerge", file: "dwarves/dwarf_male_priest_longhammer.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-red-priest", label: "Dwarf Male Red Priest", category: "Zwerge", file: "dwarves/dwarf_male_red_priest.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-shield-axe", label: "Dwarf Male Shield Axe", category: "Zwerge", file: "dwarves/dwarf_male_shield_axe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-spear", label: "Dwarf Male Spear", category: "Zwerge", file: "dwarves/dwarf_male_spear.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-spear-blue", label: "Dwarf Male Spear Blue", category: "Zwerge", file: "dwarves/dwarf_male_spear_blue.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-spear-green", label: "Dwarf Male Spear Green", category: "Zwerge", file: "dwarves/dwarf_male_spear_green.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-swords", label: "Dwarf Male Swords", category: "Zwerge", file: "dwarves/dwarf_male_swords.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-thief-dagger", label: "Dwarf Male Thief Dagger", category: "Zwerge", file: "dwarves/dwarf_male_thief_dagger.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-thief-flail", label: "Dwarf Male Thief Flail", category: "Zwerge", file: "dwarves/dwarf_male_thief_flail.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-thief-longaxe", label: "Dwarf Male Thief Longaxe", category: "Zwerge", file: "dwarves/dwarf_male_thief_longaxe.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-veteran-spear-shield", label: "Dwarf Male Veteran Spear Shield", category: "Zwerge", file: "dwarves/dwarf_male_veteran_spear_shield.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-warhammer", label: "Dwarf Male Warhammer", category: "Zwerge", file: "dwarves/dwarf_male_warhammer.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-wizard", label: "Dwarf Male Wizard", category: "Zwerge", file: "dwarves/dwarf_male_wizard.png", artist: "Devin Night" },
  { key: "dwarves-dwarf-male-wizard-staff", label: "Dwarf Male Wizard Staff", category: "Zwerge", file: "dwarves/dwarf_male_wizard_staff.png", artist: "Devin Night" },
];

export const TOKEN_ICON_BY_KEY: Record<string, TokenIcon> = Object.fromEntries(
  TOKEN_ICONS.map((i) => [i.key, i]),
);

export const TOKEN_ICON_CATEGORIES: string[] = [...new Set(TOKEN_ICONS.map((i) => i.category))];
